#!/usr/bin/env python3
#
# Copyright (c) 2010 - 2026, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"

"""Integration of the TI HALCoGen code generator into the Waf build system.

This waf tool configures the TI HalCoGen (Hardware Abstraction Layer Code
Generator, https://www.ti.com/tool/HALCOGEN) so that HAL source files can be
generated as part of the Waf build process. HALCoGen reads a ``.hcg``
configuration file (XML) together with a corresponding ``.dil`` device file
and produces C sources, assembly files, and headers for the target
microcontroller's peripherals.

.. note::
        HALCoGen is only available on Windows. On other platforms the tool
        is configured with an empty ``HALCOGEN`` variable and code generation
        tasks will be skipped.

Because the foxBMS project ships its own FreeRTOS port, the FreeRTOS sources
generated by HALCoGen are removed after generation. The only information
retained from those sources is the ``configCPU_CLOCK_HZ`` define, which is
extracted from the generated ``FreeRTOSConfig.h`` and written into a
dedicated configuration header (``config_cpu_clock_hz.h``).

Additionally, the tool validates the generated ``HL_sys_startup.c`` against
a known hash to detect unintentional changes in the startup code caused by
HALCoGen configuration modifications.

The tool is loaded in two build environments:

- **ti_arm_cgt**: The generated HAL sources are compiled and linked into the
    embedded firmware binary (features ``c`` and ``asm`` are active
    on the task generator).
- **unit_test_gcc**: The HAL sources are only generated so that their headers
    are available for include paths and mock generation during unit testing.
    They are not compiled by GCC.

Usage
-----
1. Load the tool during ``configure``::

    def configure(ctx):
        ctx.load("hcg", tooldir=TOOLDIR)

2. In a build script, declare a task generator with a ``.hcg`` source file::

    def build(bld):
        # Embedded build (ti_arm_cgt): generated sources are compiled
        bld(
            features="c asm cstlib",
            source=bld.srcnode.find_node("conf/hcg/app.hcg"),
            remove=bld.srcnode.find_node("conf/hcg/app-remove.yaml"),
            startup_hash=bld.path.find_node("app-startup.hash"),
            uselib="HAL",
            target="hal",
        )

        # Unit test build (gcc): sources are only generated, not compiled
        bld(
            source=bld.srcnode.find_node("conf/hcg/app.hcg"),
            remove=bld.srcnode.find_node("conf/hcg/app-remove.yaml"),
            startup_hash=bld.path.find_node("app-startup.hash"),
            target="hal",
        )

   The ``remove`` attribute points to a YAML file listing generated files
   that shall be deleted after code generation (e.g. FreeRTOS sources).
   The ``startup_hash`` attribute points to a file containing the expected
   hash of ``HL_sys_startup.c``.

3. When the ``c`` or ``asm`` features are present on the task generator,
   generated ``.c`` and ``.asm`` files are automatically appended to the task
   generator's ``source`` list and compiled. Otherwise only the code
   generation step is performed.

Dependencies
------------
- TI HALCoGen (Windows only, ``HALCOGEN`` executable)
- TI F021 Flash API (include and library paths resolved from HALCoGen
  installation)
- PyYAML (for parsing the remove-list configuration)
"""

import binascii
import os
import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Literal
from xml.etree import ElementTree as ET

from waflib import Errors, Logs, Task, TaskGen, Utils
from waflib.Configure import ConfigurationContext
from waflib.Node import Node
from yaml import Loader, YAMLError, load


class ToolNotSupportedError(Exception):
    """Raised when the HALCoGen configuration selects an unsupported toolchain.

    HALCoGen supports multiple compilers (TI, GCC, etc.). This project only
    supports TI-generated output. If a different toolchain is configured
    in the ``.hcg`` file, this exception aborts the build with a clear error
    message.
    """


@dataclass
class NodeStructure:
    """Parses and holds all generated file information from a HALCoGen configuration.

    Reads the ``.hcg`` XML file to determine:
    - The associated ``.dil`` device file name.
    - Whether FreeRTOS is enabled in the HALCoGen project.
    - Which header and source files will be generated.

    Files listed in the ``remove`` list are excluded from the output lists.

    Args:
        xml_file_path: Absolute path to the ``.hcg`` XML configuration file.
        remove: List of file paths that shall be excluded from the
            generated outputs.
    """

    def __init__(self, xml_file_path: str, remove: list[str]) -> None:
        """Initialize the node structure by parsing the XML root element.

        Args:
            xml_file_path: Absolute path to the ``.hcg`` XML configuration file.
            remove: List of relative file paths that shall be excluded from
                the generated output lists.
        """
        self.root = ET.parse(xml_file_path).getroot()
        self.dil_file_name = self.root.find("DEVICE").find("dilfile").text

        self.uses_freertos = False
        self.headers = []
        self.sources = []
        self.remove = remove

    def parse_xml(self) -> None:
        """Parse the HALCoGen XML to populate headers, sources, and FreeRTOS state.

        Iterates over all top-level XML elements and delegates to
        ``_parse_device`` for device/tool validation and
        ``_parse_system`` for file path extraction.

        Raises:
            ToolNotSupportedError: If the configured toolchain is not "ti".
        """
        for element in self.root:
            if element.tag == "DEVICE":
                self._parse_device(element.tag)
            else:
                self._parse_system(element.tag)

    def _parse_device(self, tag: str) -> None:
        for device_settings in self.root.iter(tag):
            for device_setting in device_settings:
                if device_setting.tag == "tools" and device_setting.text != "ti":
                    err_msg = "tool not supported"
                    raise ToolNotSupportedError(err_msg)
                if (
                    device_setting.tag == "device"
                    and device_setting.text.lower().endswith("_freertos")
                ):
                    self.uses_freertos = True

    def _parse_system(self, tag: str) -> None:
        # xml is otherwise not good parseable
        for hcg_setting in self.root.iter(tag):
            for hardware_type in list(hcg_setting[0]):
                for value_hal in list(hardware_type):
                    if value_hal.tag == "PATH":
                        if not value_hal.text:
                            continue
                        file = Path(value_hal.text).as_posix()
                        if file in self.remove:
                            continue
                        if value_hal.text.endswith(".h"):
                            self.headers.append(file)
                        elif value_hal.text.endswith((".c", ".asm")):
                            self.sources.append(file)
        self.headers = sorted(set(self.headers))
        self.sources = sorted(set(self.sources))


@TaskGen.extension(".hcg")
def process_hcg(self: TaskGen.task_gen, node: Node) -> int:
    """Create a HALCoGen code generation task from a ``.hcg`` source node.

    Parses the ``.hcg`` XML file to discover all generated outputs, loads the
    remove-list from the YAML file specified by ``self.remove``, resolves the
    corresponding ``.dil`` device file and creates an :class:`hcg_compiler`
    task that performs the actual code generation.

    A copy of the FreeRTOS sources is provided in the repository. Therefore
    the generated FreeRTOS sources are not needed and these files must be
    removed as otherwise the wrong files may be included.

    The only information needed from the generated sources is the
    ``configCPU_CLOCK_HZ``. This information is extracted from the sources
    (see :meth:`hcg_compiler.run` for details) and written into the
    configuration header ``config_cpu_clock_hz.h``

    If the ``c`` or ``asm`` features are active on the task generator, the
    generated source files are appended to ``self.source`` so that they are
    compiled in subsequent build steps. A ``.clang-format`` file disabling
    formatting is placed in the output directory to prevent accidental
    reformatting of generated code.

    Args:
        self: The task generator instance.
        node: The ``.hcg`` source node that triggered this extension handler.

    Returns:
        0 on success, 1 on failure.
    """
    remove_node = getattr(self, "remove", None)
    remove = []
    with open(remove_node.abspath(), encoding="utf-8") as f:
        remove_txt = f.read()
        try:
            remove: list = load(remove_txt, Loader=Loader)
        except YAMLError:
            self.bld.fatal("Could not load remove configuration.")
    hcg = NodeStructure(node.abspath(), remove=remove)
    try:
        hcg.parse_xml()
    except ToolNotSupportedError:
        self.bld.fatal("Unsupported tools selected in HALCoGen configuration file")
        return 1
    if not self.path or not hcg.dil_file_name:
        self.bld.fatal("object error")
        return 1
    base_path = node.path_from(self.path)
    if not base_path:
        self.bld.fatal(f"Could not determine base path of {self.path}")
        return 1
    dil_path = Path(base_path).parent / hcg.dil_file_name
    dil_node = self.path.find_node(str(dil_path))
    if not dil_node:
        self.bld.fatal(
            f"No dil file '{hcg.dil_file_name}' to hcg file '{node.abspath()}'."
        )
        return 1

    hcg_node = node
    hcg_sources = [hcg_node, dil_node]

    # we need a copy of the input sources
    copy_hcg_files = [
        self.path.find_or_declare(node.name),
        self.path.find_or_declare(dil_node.name),
    ]
    log_file = [self.path.find_or_declare(node.name.replace(node.suffix(), ".log"))]
    cpu_clock_config_header = []
    if hcg.uses_freertos:
        cpu_clock_config_header = [
            self.path.find_or_declare("include/config_cpu_clock_hz.h")
        ]
    gen_headers = [
        self.path.find_or_declare(i) for i in hcg.headers if i not in hcg.remove
    ]
    gen_sources = [
        self.path.find_or_declare(i) for i in hcg.sources if i not in hcg.remove
    ]
    tgt = (
        copy_hcg_files + log_file + cpu_clock_config_header + gen_headers + gen_sources
    )

    self.create_task(
        "hcg_compiler",
        src=hcg_sources,
        tgt=tgt,
        remove=remove,
        uses_freertos=hcg.uses_freertos,
    )
    no_clang_node = self.path.find_or_declare(".clang-format")
    if not no_clang_node.exists():
        no_clang_node.write(
            f"DisableFormat: true{os.linesep}SortIncludes: false{os.linesep}"
        )

    if any(i for i in ["c", "asm"] if i in getattr(self, "features", [])):
        self.hcg_generated_sources = []
        for i in tgt:
            if i.suffix() == ".c" or i.suffix() == ".asm":
                if i not in self.source:
                    self.source.append(i)
                    self.hcg_generated_sources.append(i)
                else:
                    pass
    return 0


class hcg_compiler(Task.Task):
    """Task that executes the HALCoGen code generator.

    Copies the ``.hcg`` and ``.dil`` input files to the build directory,
    invokes HALCoGen to generate the HAL sources, extracts the CPU clock
    frequency from the generated ``FreeRTOSConfig.h``, validates the
    ``HL_sys_startup.c`` hash, removes unwanted files, and synchronizes
    timestamps.

    Task attributes (set by :func:`process_hcg`):
        - **remove (list[str])**: File paths to delete after generation.
        - **uses_freertos (bool)**: Whether to extract the CPU clock define.
    """

    vars = ["HALCOGEN", "HALCOGEN_SRC_INPUT"]
    color = "PINK"
    ext_out = [".h", ".c", ".asm"]

    def keyword(self) -> Literal["Compiling"]:  # noqa: D102
        return "Compiling"

    def run(self) -> int:
        """Execute the HALCoGen code generator and post-process outputs.

        Performs the following steps:

        1. Copy the ``.hcg`` and ``.dil`` sources into the build directory.
        2. Run HALCoGen to generate HAL source files.
        3. If FreeRTOS is enabled, extract ``configCPU_CLOCK_HZ`` from the
           generated ``FreeRTOSConfig.h`` and write it into
           ``config_cpu_clock_hz.h``.
        4. Validate the hash of ``HL_sys_startup.c`` against the expected hash
           stored in ``self.generator.startup_hash``.
        5. Remove unwanted generated files listed in ``self.remove``.
        6. Re-copy the original ``.hcg``/``.dil`` files to overwrite the
           timestamps that HALCoGen modified during generation, keeping the
           source and build directories synchronized.

        Returns:
            0 on success, 1 if the startup file hash validation fails.
        """
        for src, tgt in zip(self.inputs[:2], self.outputs[:2], strict=False):
            shutil.copy2(src.abspath(), tgt.abspath())

        cmd = Utils.subst_vars(
            "${HALCOGEN} ${HALCOGEN_SRC_INPUT} " + self.outputs[0].abspath(),
            self.generator.env,
        ).split()
        try:
            self.generator.bld.exec_command(cmd)
        except Errors.WafError:
            self.generator.bld.fatal("Could not generate HAL sources.")
        # now we have all files that HALCoGen created, including the ones we
        # do actually not need

        cwd = self.generator.path.get_bld().abspath()
        remove_files = [Path(cwd) / i for i in self.remove]  # pylint: disable=no-member
        # get clock info from generated source 'FreeRTOSConfig.h'
        if self.uses_freertos:  # pylint: disable=no-member
            txt = ""
            try:
                txt = (Path(cwd) / "include/FreeRTOSConfig.h").read_text(
                    encoding="utf-8"
                )
            except FileNotFoundError:
                self.generator.bld.fatal("Could not find 'FreeRTOSConfig.h'.")

            frequency = None
            for line in txt.splitlines():
                regex = r"#define configCPU_CLOCK_HZ.*\( \( unsigned portLONG \) ([0-9]+) \)"
                mach = re.search(regex, line)
                if mach:
                    frequency = mach.group(1)
                    break
            if not frequency:
                self.generator.bld.fatal("Could not determine clock frequency.")
            define_guard = (
                self.outputs[3].name.replace(self.outputs[3].suffix(), "").upper()
                + "_H_"
            )
            self.outputs[3].write(
                f"#ifndef {define_guard}\n"
                f"#define {define_guard}\n"
                f"#define HALCOGEN_CPU_CLOCK_HZ ({frequency})\n"
                f"#endif /* {define_guard} */\n"
            )

        hl_sys_startup_file = Path(cwd) / "source/HL_sys_startup.c"
        if not hl_sys_startup_file.is_file():
            self.generator.bld.fatal("Could not find startup source.")
        generated_file_hash = binascii.hexlify(Utils.h_file(hl_sys_startup_file))
        known_hash = bytes(self.generator.startup_hash.read().strip(), encoding="utf-8")
        if generated_file_hash != known_hash:
            Logs.error(
                "The auto-generated file 'HL_sys_startup.c' has changed due to "
                "a configuration change in the HALCoGen project.\nThe "
                f"expected hash is {known_hash} but the generated hash is "
                f"{generated_file_hash}.\nCompare '{hl_sys_startup_file}' with "
                "'fstartup.c' and see if changes need to be applied to "
                "'fstartup.c'.\nIf everything is changed as needed, update "
                f"the hash in '{self.generator.startup_hash}' and build "
                "again.\nFor more information see the documentation "
                "(Configuration/HALCoGen)."
            )
            return 1

        # remove un-wanted generated sources
        for i in remove_files:
            i.unlink(missing_ok=True)

        # HALCoGen alters the timestamp hardcoded in the copied file after it
        # generated the sources, we do not want that, therefore overwrite the
        # altered HALCoGen files with the "original" ones
        for src, tgt in zip(self.inputs[:2], self.outputs[:2], strict=False):
            shutil.copy2(src.abspath(), tgt.abspath())
        return 0


def configure(ctx: ConfigurationContext) -> None:
    """Configure the TI HALCoGen code generator tool.

    Locates the ``HALCOGEN`` executable on the system PATH, determines the
    F021 Flash API include and library paths and stores all paths in
    ``ctx.env``.

    The following environment variables are set:
        - **HALCOGEN**: Path to the HALCoGen executable.
        - **HALCOGEN_SRC_INPUT**: Default input flag (``-i``).
        - **INCLUDES**: Extended with the F021 Flash API include path.
        - **STLIBPATH**: Extended with the F021 Flash API library path.

    .. note::
        HALCoGen is only available on Windows. On other platforms the tool
        is configured with an empty ``HALCOGEN`` variable and code generation
        tasks will be skipped.
    """
    ctx.start_msg("Checking for program 'halcogen'")
    ctx.find_program("HALCOGEN", var="HALCOGEN", mandatory=False)
    if ctx.env.HALCOGEN:
        hcg_dir = Path(ctx.env.HALCOGEN[0]).parent.parent.parent
        include_path_halcogen = hcg_dir / "F021 Flash API/02.01.01/include"
        if include_path_halcogen.exists():
            ctx.env.append_unique("INCLUDES", [str(include_path_halcogen)])

        libpath_halcogen = hcg_dir / "F021 Flash API/02.01.01"
        if libpath_halcogen.exists():
            ctx.env.append_unique("STLIBPATH", [str(libpath_halcogen)])
        ctx.env.HALCOGEN_SRC_INPUT = ["-i"]
    ctx.end_msg(ctx.env.get_flat("HALCOGEN"))
