#!/usr/bin/env python3
#
# Copyright (c) 2010 - 2026, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"


from waflib.Build import BuildContext


def build(bld: BuildContext) -> None:
    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/driver/sbc/nxpfs85xx.c"),
            bld.path.find_node("test_nxpfs85xx_mcu_spi_transfer_data.c"),
        ],
        target="test-app-nxpfs85xx_mcu_spi_transfer_data",
        includes=[
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/dma"),
            bld.srcnode.find_node("src/app/driver/fram"),
            bld.srcnode.find_node("src/app/driver/io"),
            bld.srcnode.find_node("src/app/driver/sbc"),
            bld.srcnode.find_node("src/app/driver/sbc/fs8x_driver"),
            bld.srcnode.find_node("src/app/driver/spi"),
            bld.srcnode.find_node("src/app/engine/diag"),
            bld.srcnode.find_node("src/app/engine/hw_info"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/engine/diag/diag.h"),
            bld.srcnode.find_node("src/app/driver/dma/dma.h"),
            bld.srcnode.find_node("src/app/main/include/fassert.h"),
            bld.srcnode.find_node("src/app/driver/fram/fram.h"),
            bld.srcnode.find_node("src/app/driver/io/io.h"),
            bld.srcnode.find_node("src/app/engine/hw_info/master_info.h"),
            bld.srcnode.find_node("src/app/driver/mcu/mcu.h"),
            bld.srcnode.find_node("src/app/driver/sbc/fs8x_driver/sbc_fs8x.h"),
            bld.srcnode.find_node(
                "src/app/driver/sbc/fs8x_driver/sbc_fs8x_communication.h"
            ),
            bld.srcnode.find_node("src/app/driver/spi/spi.h"),
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/driver/sbc/nxpfs85xx.c"),
            bld.path.find_node("test_nxpfs85xx.c"),
        ],
        target="test-app-nxpfs85xx",
        includes=[
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/dma"),
            bld.srcnode.find_node("src/app/driver/fram"),
            bld.srcnode.find_node("src/app/driver/io"),
            bld.srcnode.find_node("src/app/driver/sbc"),
            bld.srcnode.find_node("src/app/driver/sbc/fs8x_driver"),
            bld.srcnode.find_node("src/app/driver/spi"),
            bld.srcnode.find_node("src/app/engine/diag"),
            bld.srcnode.find_node("src/app/engine/hw_info"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/engine/diag/diag.h"),
            bld.srcnode.find_node("src/app/driver/dma/dma.h"),
            bld.srcnode.find_node("src/app/main/include/fassert.h"),
            bld.srcnode.find_node("src/app/driver/fram/fram.h"),
            bld.srcnode.find_node("src/app/driver/io/io.h"),
            bld.srcnode.find_node("src/app/engine/hw_info/master_info.h"),
            bld.srcnode.find_node("src/app/driver/mcu/mcu.h"),
            bld.srcnode.find_node("src/app/driver/sbc/fs8x_driver/sbc_fs8x.h"),
            bld.srcnode.find_node(
                "src/app/driver/sbc/fs8x_driver/sbc_fs8x_communication.h"
            ),
            bld.srcnode.find_node("src/app/driver/spi/spi.h"),
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/driver/sbc/sbc.c"),
            bld.path.find_node("test_sbc.c"),
        ],
        target="test-app-sbc",
        includes=[
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/dma"),
            bld.srcnode.find_node("src/app/driver/io"),
            bld.srcnode.find_node("src/app/driver/sbc"),
            bld.srcnode.find_node("src/app/driver/sbc/fs8x_driver"),
            bld.srcnode.find_node("src/app/driver/spi"),
            bld.srcnode.find_node("src/app/task/config"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/driver/dma/dma.h"),
            bld.srcnode.find_node("src/app/driver/io/io.h"),
            bld.srcnode.find_node("src/app/driver/mcu/mcu.h"),
            bld.srcnode.find_node("src/app/driver/sbc/nxpfs85xx.h"),
            bld.srcnode.find_node("src/app/task/os/os.h"),
            bld.srcnode.find_node(
                "src/os/freertos/freertos/portable/ccs/arm_cortex-r5/portmacro.h"
            ),
            bld.srcnode.find_node("src/app/driver/sbc/fs8x_driver/sbc_fs8x.h"),
            bld.srcnode.find_node(
                "src/app/driver/sbc/fs8x_driver/sbc_fs8x_communication.h"
            ),
            bld.srcnode.find_node("src/app/driver/spi/spi.h"),
        ],
    )
