#!/usr/bin/env python3
#
# Copyright (c) 2010 - 2026, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"

# Build the guidelines examples in order to verify that the code is valid.
# !!! This build script is not meant to be reused !!!

from collections.abc import Sequence
from dataclasses import dataclass, field

from waflib.Build import BuildContext


@dataclass
class Example:
    source: str
    includes: list[str]
    cflags: Sequence[str] = field(default_factory=list)
    use: list[str] = field(default_factory=list)


def build(bld: BuildContext) -> None:  # pylint: disable=too-many-locals
    cp = f"{bld.env.APPNAME.lower()}-config-"

    dummy_headers = [
        "config_cpu_clock_hz",
        "HL_sys_common",
        "required_different_header",
        "required_very_different_header",
        "first_used_header_1",
        "second_used_header",
        "xyz",
        "some_other_required_header",
        "some_other_required_header2",
        "required_additional_header",
        "required_additional_header2",
        "mcu",
    ]
    dummy_txt = "/* dummy file */\n"
    for i in dummy_headers:
        bld.path.find_or_declare(f"{i}.h").write(dummy_txt)
    bld.add_group()

    includes = [
        bld.path.get_bld(),
        bld.srcnode.find_node("src/app/main/include"),
    ]

    includes_freertos = [
        bld.srcnode.find_node("src/os/freertos/freertos/include"),
        bld.srcnode.find_node("src/os/freertos/freertos/portable/ccs/arm_cortex-r5"),
    ]
    includes_c_007_abc = includes + includes_freertos
    cflags_c_007_abc = ["-Wno-unknown-pragmas"]
    cflags_c_008 = ["-Wno-unused-function", "-Wno-unused-variable"]
    cflags_c_009 = ["-Wno-unused-function"]
    cflags_c_011 = ["-Wno-unused-function", "-Wno-unused-parameter"]
    cflags_c_012 = ["-Wno-unused-function", "-Wno-unused-variable"]
    cflags_c_013 = ["-Wno-unused-parameter"]
    cflags_c_015 = ["-Wno-unknown-pragmas"]
    cflags_c_016 = ["-Wno-unused-function", "-Wno-unused-variable"]
    cflags_c_017 = ["-Wno-unused-variable"]
    cflags_c_018 = ["-Wno-unknown-pragmas", "-Wno-unused-function"]
    cflags_c_021 = ["-Wno-unused-const-variable", "-Wno-unused-variable"]
    cflags_c_024 = ["-Wno-unused-function", "-Wno-unused-variable"]
    cflags_c_027 = ["-Wno-unknown-pragmas"]
    cflags_c_028 = ["-Wno-unused-function", "-Wno-unknown-pragmas"]
    includes_c_028 = includes + [bld.srcnode.find_node("src/app/application/config")]
    includes_c_006 = includes + [bld.srcnode.find_node("tools/cmock/vendor/unity/src")]
    use_c_028_battery_defines = [f"{cp}battery_system_cfg"]
    examples = [
        Example("c-004.c", includes),
        Example("c-005.c", includes),
        Example("c-006-source.c", includes),
        Example("c-006-test.c", includes_c_006),
        Example("c-007_abc.c", includes_c_007_abc, cflags_c_007_abc),
        Example("c-007_abc_cfg.c", includes),
        Example("c-008.c", includes, cflags_c_008),
        Example("c-009.c", includes, cflags_c_009),
        Example("c-011.c", includes, cflags_c_011),
        Example("c-012.c", includes, cflags_c_012),
        Example("c-013.c", includes, cflags_c_013),
        Example("c-015.c", includes, cflags_c_015),
        Example("c-016.c", includes, cflags_c_016),
        Example("c-017.c", includes, cflags_c_017),
        Example("c-018.c", includes, cflags_c_018),
        Example("c-019.c", includes),
        Example("c-020.c", includes),
        Example("c-021.c", includes, cflags_c_021),
        Example("c-022.c", includes),
        Example("c-023.c", includes),
        Example("c-024.c", includes, cflags_c_024),
        Example("c-025.c", includes),
        Example("c-026.c", includes),
        Example("c-027.c", includes, cflags_c_027),
        Example("c-028.c", includes, cflags_c_028),
        Example(
            "c-028-battery-defines.c",
            includes_c_028,
            cflags=cflags_c_028,
            use=use_c_028_battery_defines,
        ),
    ]
    for i in examples:
        bld(
            features="c",
            source=i.source,
            includes=i.includes,
            cflags=i.cflags,
            use=i.use,
            uselib="FOXBMS DOCUMENTATION",
        )
