#!/usr/bin/env python3
#
# Copyright (c) 2010 - 2026, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"

from waflib.Build import BuildContext


def build(bld: BuildContext) -> None:
    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/bootloader/driver/can/can.c"),
            bld.path.find_node("test_can.c"),
            bld.srcnode.find_node("src/bootloader/engine/boot/boot_cfg.c"),
        ],
        target="test-bl-can",
        includes=[
            bld.srcnode.find_node("src/bootloader/driver/can"),
            bld.srcnode.find_node("src/bootloader/driver/config"),
            bld.srcnode.find_node("src/bootloader/driver/rti"),
            bld.srcnode.find_node("src/bootloader/driver/mcu"),
            bld.srcnode.find_node("src/bootloader/driver/io"),
            bld.srcnode.find_node("src/bootloader/engine/boot"),
            bld.srcnode.find_node("src/bootloader/engine/can"),
            bld.srcnode.find_node("src/bootloader/main/include"),
        ],
        mocks=[
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_can.h"),
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_het.h"),
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_reg_can.h"),
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_reg_system.h"),
            bld.srcnode.find_node(
                "src/bootloader/driver/can/can_bootloader-version-info.h"
            ),
            bld.srcnode.find_node("src/bootloader/engine/can/can_cbs.h"),
            bld.srcnode.find_node("src/bootloader/driver/config/can_cfg.h"),
            bld.srcnode.find_node("src/bootloader/driver/can/can_helper.h"),
            bld.srcnode.find_node("src/bootloader/driver/io/io.h"),
            bld.srcnode.find_node("src/bootloader/driver/rti/rti.h"),
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/bootloader/driver/can/can_helper.c"),
            bld.path.find_node("test_can_helper.c"),
        ],
        target="test-bl-can_helper",
        includes=[
            bld.srcnode.find_node("src/bootloader/driver/can"),
            bld.srcnode.find_node("src/bootloader/driver/config"),
            bld.srcnode.find_node("src/bootloader/engine/boot"),
            bld.srcnode.find_node("src/bootloader/main/include"),
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/bootloader/driver/can/can.c"),
            bld.path.find_node("test_can_can_message_notification.c"),
        ],
        target="test-bl-can_can_message_notification",
        includes=[
            bld.srcnode.find_node("src/bootloader/driver/can"),
            bld.srcnode.find_node("src/bootloader/driver/config"),
            bld.srcnode.find_node("src/bootloader/driver/rti"),
            bld.srcnode.find_node("src/bootloader/driver/mcu"),
            bld.srcnode.find_node("src/bootloader/driver/io"),
            bld.srcnode.find_node("src/bootloader/engine/boot"),
            bld.srcnode.find_node("src/bootloader/engine/can"),
        ],
        mocks=[
            bld.srcnode.find_node("src/bootloader/engine/boot/boot_cfg.h"),
            bld.srcnode.find_node(
                "src/bootloader/driver/can/can_bootloader-version-info.h"
            ),
            bld.srcnode.find_node("src/bootloader/engine/can/can_cbs.h"),
            bld.srcnode.find_node("src/bootloader/driver/config/can_cfg.h"),
            bld.srcnode.find_node("src/bootloader/driver/can/can_helper.h"),
            bld.srcnode.find_node("src/bootloader/driver/io/io.h"),
            bld.srcnode.find_node("src/bootloader/driver/mcu/mcu.h"),
            bld.srcnode.find_node("src/bootloader/driver/rti/rti.h"),
        ],
        defines=["COMPILE_FOR_UNIT_TEST=1"],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node(
                "src/bootloader/driver/can/can_bootloader-version-info.c"
            ),
            bld.path.find_node("test_can_bootloader-version-info.c"),
        ],
        target="test-bl-can_bootloader-version-info",
        includes=[
            bld.srcnode.find_node("src/bootloader/driver/can"),
            bld.srcnode.find_node("src/bootloader/driver/config"),
            bld.srcnode.find_node("src/bootloader/driver/foxmath"),
            bld.srcnode.find_node("src/bootloader/main/include"),
            bld.srcnode.find_node("src/bootloader/engine/can"),
            bld.srcnode.find_node("src/bootloader/engine/boot"),
            bld.srcnode.find_node("src/version"),
        ],
        mocks=[
            bld.srcnode.find_node("src/bootloader/driver/can/can.h"),
            bld.srcnode.find_node("src/bootloader/driver/config/can_cfg.h"),
            bld.srcnode.find_node("src/bootloader/driver/can/can_helper.h"),
            bld.srcnode.find_node("src/bootloader/driver/foxmath/foxmath.h"),
            bld.srcnode.find_node("src/bootloader/driver/foxmath/utils.h"),
        ],
    )
