#!/usr/bin/env python3
#
# Copyright (c) 2010 - 2026, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"

from waflib.Build import BuildContext


def build(bld: BuildContext) -> None:
    op = f"{bld.env.APPNAME.lower()}-object-"
    lp = f"{bld.env.APPNAME.lower()}-"
    ip = f"{bld.env.APPNAME.lower()}-incpath-"
    cp = f"{bld.env.APPNAME.lower()}-config-"

    bld.recurse(["api", "config", "vendor"])

    use = [
        f"{lp}hal",
        f"{ip}afe",
        f"{ip}rtos-kernel",
        f"{cp}battery_cell_cfg",
    ]

    includes = [
        bld.srcnode.find_node("src/app/application/config"),
        bld.srcnode.find_node("src/app/driver/afe/nxp/common/mc3377x/vendor"),
        bld.srcnode.find_node("src/app/driver/config"),
        bld.srcnode.find_node("src/app/driver/dma"),
        bld.srcnode.find_node("src/app/driver/foxmath"),
        bld.srcnode.find_node("src/app/driver/io"),
        bld.srcnode.find_node("src/app/driver/mcu"),
        bld.srcnode.find_node("src/app/driver/pex"),
        bld.srcnode.find_node("src/app/driver/rtc"),
        bld.srcnode.find_node("src/app/driver/spi"),
        bld.srcnode.find_node("src/app/driver/ts"),
        bld.srcnode.find_node("src/app/driver/ts/api"),
        bld.srcnode.find_node("src/app/engine/config"),
        bld.srcnode.find_node("src/app/engine/database"),
        bld.srcnode.find_node("src/app/engine/diag"),
        bld.srcnode.find_node("src/app/main/include"),
        bld.srcnode.find_node("src/app/task/config"),
        bld.srcnode.find_node("src/app/task/ftask"),
        bld.srcnode.find_node("src/app/task/os"),
    ]
    source = "nxp_mc33775a_alarm"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        use=use,
        uselib="FOXBMS",
        target=f"{op}{source}",
    )
    source = "nxp_mc33775a_balancing"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        use=use,
        uselib="FOXBMS",
        target=f"{op}{source}",
    )

    source = "nxp_mc33775a_i2c"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        use=use,
        uselib="FOXBMS",
        target=f"{op}{source}",
    )
    source = "nxp_mc33775a_measurement"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        use=use,
        uselib="FOXBMS",
        target=f"{op}{source}",
    )

    bld(
        export_includes=[
            bld.path,
            bld.path.find_node("api"),
            bld.path.find_node("config"),
            bld.path.find_node("vendor"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/api"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/common/mc3377x"),
            bld.srcnode.find_node("src/app/driver/afe/api"),
        ],
        target=f"{ip}afe-nxp_mc33775a",
    )

    use = [
        f"{op}uc_msg_t",
        f"{op}nxp_afe",
        f"{op}nxp_mc3377x_afe_dma",
        f"{op}nxp_mc3377x_database",
        f"{op}nxp_mc3377x_helpers",
        f"{op}nxp_mc3377x_mux",
        f"{op}nxp_mc3377x-ll",
        f"{op}nxp_mc3377x",
        f"{op}nxp_mc33775a_afe",
        f"{op}nxp_mc33775a_cfg",
        f"{op}nxp_mc33775a_alarm",
        f"{op}nxp_mc33775a_balancing",
        f"{op}nxp_mc33775a_i2c",
        f"{op}nxp_mc33775a_measurement",
    ]
    bld(
        features="c cstlib",
        use=use,
        target=f"{lp}afe",
    )
