/**
 *
 * @copyright &copy; 2010 - 2026, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * We kindly request you to use one or more of the following phrases to refer to
 * foxBMS in your hardware, software, documentation or advertising materials:
 *
 * - "This product uses parts of foxBMS&reg;"
 * - "This product includes parts of foxBMS&reg;"
 * - "This product is derived from foxBMS&reg;"
 *
 */

/**
 * @file    nxp_mc3377x_reg_def.h
 * @author  foxBMS Team
 * @date    2025-06-25 (date of creation)
 * @updated 2026-04-20 (date of last update)
 * @version v1.11.0
 * @ingroup DRIVERS
 * @prefix  N77X
 *
 * @brief   Wrapper file for mapping to the MC3377X vendor headers
 * @details TODO
 */

#ifndef FOXBMS__NXP_MC3377X_REG_DEF_H_
#define FOXBMS__NXP_MC3377X_REG_DEF_H_

/*========== Includes =======================================================*/
#include "foxbms_config.h"

#if defined(FOXBMS_AFE_DRIVER_NXP_MC33775A)
#include "MC33775A.h"
#endif

/*========== Macros and Definitions =========================================*/
#if defined(FOXBMS_AFE_DRIVER_NXP_MC33775A)

/* Balancing */
#define MC3377X_BAL_CH_CFG_OFFSET                   (MC33775_BAL_CH_CFG_OFFSET)
#define MC3377X_BAL_GLOB_TO_TMR_OFFSET              (MC33775_BAL_GLOB_TO_TMR_OFFSET)
#define MC3377X_BAL_PRE_TMR_OFFSET                  (MC33775_BAL_PRE_TMR_OFFSET)
#define MC3377X_BAL_TMR_CH_ALL_OFFSET               (MC33775_BAL_TMR_CH_ALL_OFFSET)
#define MC3377X_BAL_TMR_CH_ALL_PWM_PWM100_ENUM_VAL  (MC33775_BAL_TMR_CH_ALL_PWM_PWM100_ENUM_VAL)
#define MC3377X_BAL_TMR_CH_ALL_PWM_POS              (MC33775_BAL_TMR_CH_ALL_PWM_POS)
#define MC3377X_BAL_TMR_CH_ALL_BALTIME_POS          (MC33775_BAL_TMR_CH_ALL_BALTIME_POS)
#define MC3377X_BAL_GLOB_CFG_OFFSET                 (MC33775_BAL_GLOB_CFG_OFFSET)
#define MC3377X_BAL_GLOB_CFG_BALEN_ENABLED_ENUM_VAL (MC33775_BAL_GLOB_CFG_BALEN_ENABLED_ENUM_VAL)
#define MC3377X_BAL_GLOB_CFG_BALEN_POS              (MC33775_BAL_GLOB_CFG_BALEN_POS)
#define MC3377X_BAL_GLOB_CFG_TMRBALEN_STOP_ENUM_VAL (MC33775_BAL_GLOB_CFG_TMRBALEN_STOP_ENUM_VAL)
#define MC3377X_BAL_GLOB_CFG_TMRBALEN_POS           (MC33775_BAL_GLOB_CFG_TMRBALEN_POS)

/* I2C / Mux */
#define MC3377X_I2C_DATA0_OFFSET                (MC33775_I2C_DATA0_OFFSET)
#define MC3377X_I2C_DATA0_BYTE0_POS             (MC33775_I2C_DATA0_BYTE0_POS)
#define MC3377X_I2C_DATA0_BYTE1_POS             (MC33775_I2C_DATA0_BYTE1_POS)
#define MC3377X_I2C_DATA1_OFFSET                (MC33775_I2C_DATA1_OFFSET)
#define MC3377X_I2C_DATA1_BYTE2_POS             (MC33775_I2C_DATA1_BYTE2_POS)
#define MC3377X_I2C_DATA1_BYTE3_POS             (MC33775_I2C_DATA1_BYTE3_POS)
#define MC3377X_I2C_CTRL_OFFSET                 (MC33775_I2C_CTRL_OFFSET)
#define MC3377X_I2C_CTRL_START_POS              (MC33775_I2C_CTRL_START_POS)
#define MC3377X_I2C_CTRL_STPAFTER_STOP_ENUM_VAL (MC33775_I2C_CTRL_STPAFTER_STOP_ENUM_VAL)
#define MC3377X_I2C_CTRL_STPAFTER_POS           (MC33775_I2C_CTRL_STPAFTER_POS)
#define MC3377X_I2C_CTRL_RDAFTER_POS            (MC33775_I2C_CTRL_RDAFTER_POS)
#define MC3377X_I2C_STAT_OFFSET                 (MC33775_I2C_STAT_OFFSET)
#define MC3377X_I2C_STAT_PENDING_MSK            (MC33775_I2C_STAT_PENDING_MSK)
#define MC3377X_I2C_STAT_NACKRCV_MSK            (MC33775_I2C_STAT_NACKRCV_MSK)
#define MC3377X_I2C_CFG_OFFSET                  (MC33775_I2C_CFG_OFFSET)
#define MC3377X_I2C_CFG_EN_ENABLED_ENUM_VAL     (MC33775_I2C_CFG_EN_ENABLED_ENUM_VAL)
#define MC3377X_I2C_CFG_EN_POS                  (MC33775_I2C_CFG_EN_POS)
#define MC3377X_I2C_CFG_CLKSEL_F_400K_ENUM_VAL  (MC33775_I2C_CFG_CLKSEL_F_400K_ENUM_VAL)
#define MC3377X_I2C_CFG_CLKSEL_POS              (MC33775_I2C_CFG_CLKSEL_POS)

/* Enumerate */
#define MC3377X_SYS_VERSION_OFFSET                     (MC33775_SYS_VERSION_OFFSET)
#define MC3377X_SYS_MODE_OFFSET                        (MC33775_SYS_MODE_OFFSET)
#define MC3377X_SYS_MODE_TARGETMODE_DEEPSLEEP_ENUM_VAL (MC33775_SYS_MODE_TARGETMODE_DEEPSLEEP_ENUM_VAL)
#define MC3377X_SYS_MODE_TARGETMODE_POS                (MC33775_SYS_MODE_TARGETMODE_POS)
#define MC3377X_SYS_COM_CFG_OFFSET                     (MC33775_SYS_COM_CFG_OFFSET)
#define MC3377X_SYS_COM_CFG_BUSFW_ENABLED_ENUM_VAL     (MC33775_SYS_COM_CFG_BUSFW_ENABLED_ENUM_VAL)
#define MC3377X_SYS_COM_CFG_BUSFW_POS                  (MC33775_SYS_COM_CFG_BUSFW_POS)
#define MC3377X_SYS_COM_TO_CFG_OFFSET                  (MC33775_SYS_COM_TO_CFG_OFFSET)
#define MC3377X_SYS_COM_TO_CFG_COMTODISABLE_POS        (MC33775_SYS_COM_TO_CFG_COMTODISABLE_POS)
#define MC3377X_SYS_COM_TO_CFG_COMTO_POS               (MC33775_SYS_COM_TO_CFG_COMTO_POS)
#define MC3377X_SYS_UID_LOW_OFFSET                     (MC33775_SYS_UID_LOW_OFFSET)

/* Measurement */
#define MC3377X_ALLM_APP_CTRL_OFFSET                    (MC33775_ALLM_APP_CTRL_OFFSET)
#define MC3377X_ALLM_APP_CTRL_PAUSEBAL_POS              (MC33775_ALLM_APP_CTRL_PAUSEBAL_POS)
#define MC3377X_PRMM_APP_CTRL_CAPVC_POS                 (MC33775_PRMM_APP_CTRL_CAPVC_POS)
#define MC3377X_PRMM_APP_CTRL_VCOLNUM_DISABLED_ENUM_VAL (MC33775_PRMM_APP_CTRL_VCOLNUM_DISABLED_ENUM_VAL)
#define MC3377X_PRMM_APP_CTRL_VCOLNUM_POS               (MC33775_PRMM_APP_CTRL_VCOLNUM_POS)
#define MC3377X_PRMM_APP_VC_CNT_OFFSET                  (MC33775_PRMM_APP_VC_CNT_OFFSET)
#define MC3377X_SECM_APP_AIN4_OFFSET                    (MC33775_SECM_APP_AIN4_OFFSET)
#define MC3377X_SECM_PER_NPNISENSE_OFFSET               (MC33775_SECM_PER_NPNISENSE_OFFSET)
#define MC3377X_ALLM_VCVB_CFG_OFFSET                    (MC33775_ALLM_VCVB_CFG_OFFSET)
#define MC3377X_PRMM_AIN_CFG_OFFSET                     (MC33775_PRMM_AIN_CFG_OFFSET)
#define MC3377X_SECM_AIN_CFG_OFFSET                     (MC33775_SECM_AIN_CFG_OFFSET)
#define MC3377X_ALLM_CFG_OFFSET                         (MC33775_ALLM_CFG_OFFSET)
#define MC3377X_ALLM_CFG_BALPAUSELEN_POS                (MC33775_ALLM_CFG_BALPAUSELEN_POS)
#define MC3377X_ALLM_CFG_MEASEN_POS                     (MC33775_ALLM_CFG_MEASEN_POS)

/* Alarm / Events */
#define MC3377X_PRMM_VC_OV_UV_CFG_OFFSET        (MC33775_PRMM_VC_OV_UV_CFG_OFFSET)
#define MC3377X_PRMM_VC_OV_TH_CFG_OFFSET        (MC33775_PRMM_VC_OV_TH_CFG_OFFSET)
#define MC3377X_PRMM_VC_UV0_TH_CFG_OFFSET       (MC33775_PRMM_VC_UV0_TH_CFG_OFFSET)
#define MC3377X_PRMM_VC_UV1_TH_CFG_OFFSET       (MC33775_PRMM_VC_UV1_TH_CFG_OFFSET)
#define MC3377X_FEH_ALARM_OUT_CFG_SYSFLTEVT_POS (MC33775_FEH_ALARM_OUT_CFG_SYSFLTEVT_POS)
#define MC3377X_FEH_ALARM_OUT_CFG_BALRDY_POS    (MC33775_FEH_ALARM_OUT_CFG_BALRDY_POS)
#define MC3377X_FEH_ALARM_OUT_CFG_WAKEUPIN_POS  (MC33775_FEH_ALARM_OUT_CFG_WAKEUPIN_POS)
#define MC3377X_FEH_ALARM_OUT_CFG_ALARMIN_POS   (MC33775_FEH_ALARM_OUT_CFG_ALARMIN_POS)
#define MC3377X_FEH_ALARM_OUT_CFG_AIN3UV_POS    (MC33775_FEH_ALARM_OUT_CFG_AIN3UV_POS)
#define MC3377X_FEH_ALARM_OUT_CFG_AIN3OV_POS    (MC33775_FEH_ALARM_OUT_CFG_AIN3OV_POS)
#define MC3377X_FEH_ALARM_OUT_CFG_AIN2UV_POS    (MC33775_FEH_ALARM_OUT_CFG_AIN2UV_POS)
#define MC3377X_FEH_ALARM_OUT_CFG_AIN2OV_POS    (MC33775_FEH_ALARM_OUT_CFG_AIN2OV_POS)
#define MC3377X_FEH_ALARM_OUT_CFG_AIN1UV_POS    (MC33775_FEH_ALARM_OUT_CFG_AIN1UV_POS)
#define MC3377X_FEH_ALARM_OUT_CFG_AIN1OV_POS    (MC33775_FEH_ALARM_OUT_CFG_AIN1OV_POS)
#define MC3377X_FEH_ALARM_OUT_CFG_AIN0UV_POS    (MC33775_FEH_ALARM_OUT_CFG_AIN0UV_POS)
#define MC3377X_FEH_ALARM_OUT_CFG_AIN0OV_POS    (MC33775_FEH_ALARM_OUT_CFG_AIN0OV_POS)
#define MC3377X_FEH_ALARM_OUT_CFG_VCUV1_POS     (MC33775_FEH_ALARM_OUT_CFG_VCUV1_POS)
#define MC3377X_FEH_ALARM_OUT_CFG_VCUV0_POS     (MC33775_FEH_ALARM_OUT_CFG_VCUV0_POS)
#define MC3377X_FEH_ALARM_OUT_CFG_VCOV_POS      (MC33775_FEH_ALARM_OUT_CFG_VCOV_POS)

#define MC3377X_FEH_SUPPLY_FLT_EVT_CFG0_VDDCUVEN_POS       (MC33775_FEH_SUPPLY_FLT_EVT_CFG0_VDDCUVEN_POS)
#define MC3377X_FEH_SUPPLY_FLT_EVT_CFG0_VDDCOVEN_POS       (MC33775_FEH_SUPPLY_FLT_EVT_CFG0_VDDCOVEN_POS)
#define MC3377X_FEH_SUPPLY_FLT_EVT_CFG0_VAUXUVEN_POS       (MC33775_FEH_SUPPLY_FLT_EVT_CFG0_VAUXUVEN_POS)
#define MC3377X_FEH_SUPPLY_FLT_EVT_CFG0_VAUXOVEN_POS       (MC33775_FEH_SUPPLY_FLT_EVT_CFG0_VAUXOVEN_POS)
#define MC3377X_FEH_SUPPLY_FLT_EVT_CFG0_VPREREFSUVEN_POS   (MC33775_FEH_SUPPLY_FLT_EVT_CFG0_VPREREFSUVEN_POS)
#define MC3377X_FEH_SUPPLY_FLT_EVT_CFG0_IBIASPERMUCEN_POS  (MC33775_FEH_SUPPLY_FLT_EVT_CFG0_IBIASPERMUCEN_POS)
#define MC3377X_FEH_SUPPLY_FLT_EVT_CFG0_IBIASPERMOCEN_POS  (MC33775_FEH_SUPPLY_FLT_EVT_CFG0_IBIASPERMOCEN_POS)
#define MC3377X_FEH_SUPPLY_FLT_EVT_CFG0_AFECPUVEN_POS      (MC33775_FEH_SUPPLY_FLT_EVT_CFG0_AFECPUVEN_POS)
#define MC3377X_FEH_SUPPLY_FLT_EVT_CFG0_AFECPOVEN_POS      (MC33775_FEH_SUPPLY_FLT_EVT_CFG0_AFECPOVEN_POS)
#define MC3377X_FEH_SUPPLY_FLT_EVT_CFG0_V2P5AUVEN_POS      (MC33775_FEH_SUPPLY_FLT_EVT_CFG0_V2P5AUVEN_POS)
#define MC3377X_FEH_SUPPLY_FLT_EVT_CFG0_V2P5AOVEN_POS      (MC33775_FEH_SUPPLY_FLT_EVT_CFG0_V2P5AOVEN_POS)
#define MC3377X_FEH_SUPPLY_FLT_EVT_CFG0_VDDAUVEN_POS       (MC33775_FEH_SUPPLY_FLT_EVT_CFG0_VDDAUVEN_POS)
#define MC3377X_FEH_SUPPLY_FLT_EVT_CFG0_VDDAOVEN_POS       (MC33775_FEH_SUPPLY_FLT_EVT_CFG0_VDDAOVEN_POS)
#define MC3377X_FEH_SUPPLY_FLT_EVT_CFG0_VBATOVEN_POS       (MC33775_FEH_SUPPLY_FLT_EVT_CFG0_VBATOVEN_POS)
#define MC3377X_FEH_SUPPLY_FLT_EVT_CFG1_VPREOVEN_POS       (MC33775_FEH_SUPPLY_FLT_EVT_CFG1_VPREOVEN_POS)
#define MC3377X_FEH_SUPPLY_FLT_EVT_CFG1_VDDIOUVEN_POS      (MC33775_FEH_SUPPLY_FLT_EVT_CFG1_VDDIOUVEN_POS)
#define MC3377X_FEH_SUPPLY_FLT_EVT_CFG1_VDDIOOVEN_POS      (MC33775_FEH_SUPPLY_FLT_EVT_CFG1_VDDIOOVEN_POS)
#define MC3377X_FEH_SUPPLY_FLT_EVT_CFG1_VDDCHCEN_POS       (MC33775_FEH_SUPPLY_FLT_EVT_CFG1_VDDCHCEN_POS)
#define MC3377X_FEH_SUPPLY_FLT_EVT_CFG1_VPREREFSOVEN_POS   (MC33775_FEH_SUPPLY_FLT_EVT_CFG1_VPREREFSOVEN_POS)
#define MC3377X_FEH_SUPPLY_FLT_EVT_CFG1_VBATLVEN_POS       (MC33775_FEH_SUPPLY_FLT_EVT_CFG1_VBATLVEN_POS)
#define MC3377X_FEH_ANA_FLT_EVT_CFG_FUSEFLTEN_POS          (MC33775_FEH_ANA_FLT_EVT_CFG_FUSEFLTEN_POS)
#define MC3377X_FEH_ANA_FLT_EVT_CFG_BALFLTEN_POS           (MC33775_FEH_ANA_FLT_EVT_CFG_BALFLTEN_POS)
#define MC3377X_FEH_ANA_FLT_EVT_CFG_MONBISTEN_POS          (MC33775_FEH_ANA_FLT_EVT_CFG_MONBISTEN_POS)
#define MC3377X_FEH_COM_FLT_EVT_CFG_RSPLENERREN_POS        (MC33775_FEH_COM_FLT_EVT_CFG_RSPLENERREN_POS)
#define MC3377X_FEH_COM_FLT_EVT_CFG_ERRCNTOFEN_POS         (MC33775_FEH_COM_FLT_EVT_CFG_ERRCNTOFEN_POS)
#define MC3377X_FEH_COM_FLT_EVT_CFG_CRCERREN_POS           (MC33775_FEH_COM_FLT_EVT_CFG_CRCERREN_POS)
#define MC3377X_FEH_COM_FLT_EVT_CFG_FRAMEERREN_POS         (MC33775_FEH_COM_FLT_EVT_CFG_FRAMEERREN_POS)
#define MC3377X_FEH_MEAS_FLT_EVT_CFG_SYNCMEASFLTEN_POS     (MC33775_FEH_MEAS_FLT_EVT_CFG_SYNCMEASFLTEN_POS)
#define MC3377X_FEH_MEAS_FLT_EVT_CFG_SECCALCRCFLTEN_POS    (MC33775_FEH_MEAS_FLT_EVT_CFG_SECCALCRCFLTEN_POS)
#define MC3377X_FEH_MEAS_FLT_EVT_CFG_PRIMCALCRCFLTEN_POS   (MC33775_FEH_MEAS_FLT_EVT_CFG_PRIMCALCRCFLTEN_POS)
#define MC3377X_FEH_SUPPLY_FLT_EVT_CFG0_OFFSET             (MC33775_FEH_SUPPLY_FLT_EVT_CFG0_OFFSET)
#define MC3377X_FEH_SUPPLY_FLT_EVT_CFG1_OFFSET             (MC33775_FEH_SUPPLY_FLT_EVT_CFG1_OFFSET)
#define MC3377X_FEH_ANA_FLT_EVT_CFG_OFFSET                 (MC33775_FEH_ANA_FLT_EVT_CFG_OFFSET)
#define MC3377X_FEH_COM_FLT_EVT_CFG_OFFSET                 (MC33775_FEH_COM_FLT_EVT_CFG_OFFSET)
#define MC3377X_FEH_MEAS_FLT_EVT_CFG_OFFSET                (MC33775_FEH_MEAS_FLT_EVT_CFG_OFFSET)
#define MC3377X_FEH_ALARM_OUT_CFG_OFFSET                   (MC33775_FEH_ALARM_OUT_CFG_OFFSET)
#define MC3377X_FEH_ALARM_OUT_REASON_OFFSET                (MC33775_FEH_ALARM_OUT_REASON_OFFSET)
#define MC3377X_FEH_SUPPLY_FLT_STAT0_OFFSET                (MC33775_FEH_SUPPLY_FLT_STAT0_OFFSET)
#define MC3377X_FEH_SUPPLY_FLT_STAT1_OFFSET                (MC33775_FEH_SUPPLY_FLT_STAT1_OFFSET)
#define MC3377X_FEH_ANA_FLT_STAT_OFFSET                    (MC33775_FEH_ANA_FLT_STAT_OFFSET)
#define MC3377X_FEH_COM_FLT_STAT_OFFSET                    (MC33775_FEH_COM_FLT_STAT_OFFSET)
#define MC3377X_FEH_MEAS_FLT_STAT_OFFSET                   (MC33775_FEH_MEAS_FLT_STAT_OFFSET)
#define MC3377X_FEH_ALARM_CFG_ALARMIN_LOW_ACTIVE_ENUM_VAL  (MC33775_FEH_ALARM_CFG_ALARMIN_LOW_ACTIVE_ENUM_VAL)
#define MC3377X_FEH_ALARM_CFG_ALARMIN_POS                  (MC33775_FEH_ALARM_CFG_ALARMIN_POS)
#define MC3377X_FEH_ALARM_CFG_ALARMOUT_LOW_ACTIVE_ENUM_VAL (MC33775_FEH_ALARM_CFG_ALARMOUT_LOW_ACTIVE_ENUM_VAL)
#define MC3377X_FEH_ALARM_CFG_ALARMOUT_POS                 (MC33775_FEH_ALARM_CFG_ALARMOUT_POS)
#define MC3377X_FEH_ALARM_CFG_OFFSET                       (MC33775_FEH_ALARM_CFG_OFFSET)
#define MC3377X_FEH_ALARM_CFG_ALARMIN_MSK                  (MC33775_FEH_ALARM_CFG_ALARMIN_MSK)

#endif

/*========== Extern Constant and Variable Declarations ======================*/

/*========== Extern Function Prototypes =====================================*/

/*========== Externalized Static Functions Prototypes (Unit Test) ===========*/
#ifdef UNITY_UNIT_TEST
#endif

#endif /* FOXBMS__NXP_MC3377X_REG_DEF_H_ */
