#!/usr/bin/env python3
#
# Copyright (c) 2010 - 2026, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"

# !!! This build script is not meant to be reused !!!

from waflib.Build import BuildContext


def build(bld: BuildContext) -> None:
    cp = f"{bld.env.APPNAME.lower()}-config-"

    dummy_txt = "/* dummy file */\n"
    dummy_headers = ["mcu", "HL_can", "os", "foxbms_config_bms_slave"]
    for i in dummy_headers:
        bld.path.find_or_declare(f"{i}.h").write(dummy_txt)
    includes = [
        bld.bldnode.find_or_declare("src/app/application/config"),
        bld.path.get_bld(),
        bld.srcnode.find_node("src/app/application/config"),
        bld.srcnode.find_node("src/app/driver/config"),
        bld.srcnode.find_node("src/app/driver/fram"),
        bld.srcnode.find_node("src/app/engine/config"),
        bld.srcnode.find_node("src/app/engine/database"),
        bld.srcnode.find_node("src/app/main/include"),
    ]

    use = f"{cp}battery_system_cfg"
    bld(
        features="c",
        source="can_how-to_tx_cyclic.c",
        defines=[
            "MCU_ADC1_MAX_NR_CHANNELS=1",
            "OS_QUEUE=void",
            "canBASE_t=void",
            'canREG1="((uint32_t *)0xFFF7DC00U)"',
        ],
        includes=includes,
        cflags=["-Wno-unused-parameter", "-Wno-unknown-pragmas"],
        use=use,
        uselib="FOXBMS DOCUMENTATION",
    )

    async_extra_includes = [
        bld.srcnode.find_node("src/app/driver/can/cbs/tx-async"),
        bld.srcnode.find_node("fram"),
    ]
    bld(
        features="c",
        source="can_how-to_tx_async.c",
        defines=[
            "MCU_ADC1_MAX_NR_CHANNELS=1",
            "OS_QUEUE=void",
            "canBASE_t=void",
            'canREG1="((uint32_t *)0xFFF7DC00U)"',
        ],
        includes=includes + async_extra_includes,
        cflags=["-Wno-unused-parameter", "-Wno-unknown-pragmas"],
        use=use,
        uselib="FOXBMS DOCUMENTATION",
    )
