#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (c) 2010 - 2021, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"

"""Build Script: ``./docs/software/modules/task/ftask/wscript``
===============================================================

Builds the ftask example

This build script is not meant to be reused!

"""

import os


def build(bld):
    """Build the database object"""
    source = ["ftask_how-to.c"]
    includes = [
        ".",
        os.path.join("..", "..", "..", "..", "..", "src", "app", "main", "include"),
    ]
    cflags = bld.env.CFLAGS_FOXBMS
    bld.path.find_or_declare("HL_sys_common.h").write(
        "/* dummy file */\n"
        "extern void OS_EnterTaskCritical();\n"
        "extern void OS_ExitTaskCritical();\n"
    )
    bld.path.find_or_declare("HL_gio.h").write(
        "/* dummy file */\n"
        "typedef uint32_t uint32;\n"
        "typedef volatile struct gioPort {\n"
        "uint32 DIR;\n"
        "uint32 DIN;\n"
        "uint32 DOUT;\n"
        "uint32 DSET;\n"
        "uint32 DCLR;\n"
        "uint32 PDR;\n"
        "uint32 PULDIS;\n"
        "uint32 PSL;\n"
        "} gioPORT_t;\n"
        "#define gioPORTB ((gioPORT_t *)0xFFF7BC54U)\n"
        "void gioSetBit(gioPORT_t *port, uint32 bit, uint32 value);\n"
        "uint32 gioGetBit(gioPORT_t *port, uint32 bit);\n"
    )
    bld.add_group()
    bld(
        features="c",
        source=source,
        includes=includes,
        cflags=(cflags + ["--diag_suppress=179", "--diag_suppress=552"]),
    )
