// @prefix  MM

#ifndef FOXBMS__CODING_STYLE_NAMING_MACRO_INVALID_H_
#define FOXBMS__CODING_STYLE_NAMING_MACRO_INVALID_H_

#define MM_FOO
#define MM_BAR (1u)

#endif /* FOXBMS__CODING_STYLE_NAMING_MACRO_H_ */
