#!/usr/bin/env python3
#
# Copyright (c) 2010 - 2025, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"

"""Build the FreeRTOS Plus TCP library"""


def build(bld):
    """Build the FreeRTOS Plus TCP library"""
    source = [
        "FreeRTOS_ARP.c",
        "FreeRTOS_BitConfig.c",
        "FreeRTOS_DHCP.c",
        "FreeRTOS_DHCPv6.c",
        "FreeRTOS_DNS.c",
        "FreeRTOS_DNS_Cache.c",
        "FreeRTOS_DNS_Callback.c",
        "FreeRTOS_DNS_Networking.c",
        "FreeRTOS_DNS_Parser.c",
        "FreeRTOS_ICMP.c",
        "FreeRTOS_IP.c",
        "FreeRTOS_IP_Timers.c",
        "FreeRTOS_IP_Utils.c",
        "FreeRTOS_IPv4.c",
        "FreeRTOS_IPv4_Sockets.c",
        "FreeRTOS_IPv4_Utils.c",
        "FreeRTOS_IPv6.c",
        "FreeRTOS_IPv6_Sockets.c",
        "FreeRTOS_IPv6_Utils.c",
        "FreeRTOS_ND.c",
        "FreeRTOS_RA.c",
        "FreeRTOS_Routing.c",
        "FreeRTOS_Sockets.c",
        "FreeRTOS_Stream_Buffer.c",
        "FreeRTOS_TCP_IP.c",
        "FreeRTOS_TCP_IP_IPv4.c",
        "FreeRTOS_TCP_IP_IPv6.c",
        "FreeRTOS_TCP_Reception.c",
        "FreeRTOS_TCP_State_Handling.c",
        "FreeRTOS_TCP_State_Handling_IPv4.c",
        "FreeRTOS_TCP_State_Handling_IPv6.c",
        "FreeRTOS_TCP_Transmission.c",
        "FreeRTOS_TCP_Transmission_IPv4.c",
        "FreeRTOS_TCP_Transmission_IPv6.c",
        "FreeRTOS_TCP_Utils.c",
        "FreeRTOS_TCP_Utils_IPv4.c",
        "FreeRTOS_TCP_Utils_IPv6.c",
        "FreeRTOS_TCP_WIN.c",
        "FreeRTOS_Tiny_TCP.c",
        "FreeRTOS_UDP_IP.c",
        "FreeRTOS_UDP_IPv4.c",
        "FreeRTOS_UDP_IPv6.c",
    ]
    includes = ["include", "portable/Compiler/CCS"]
    includes.extend(bld.env.INCLUDES_RTOS)

    target = f"{bld.env.APPNAME.lower()}-tcp"
    use = f"{bld.env.APPNAME.lower()}-os"
    cflags = bld.env.C

    bld.stlib(
        source=source,
        includes=includes,
        cflags=cflags,
        use=use,
        target=target,
    )
