#!/usr/bin/env python3
#
# Copyright (c) 2010 - 2026, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"


def build(bld):  # pylint: disable=too-many-statements
    op = f"{bld.env.APPNAME.lower()}-object-"
    lp = f"{bld.env.APPNAME.lower()}-"

    bld.recurse("portable")

    # When ipconfigUSE_TCP_WIN is set to 0, some static functions are not called.
    # This is why diag_suppress=179 has to be used on FreeRTOS_TCP_WIN.c.
    includes_win = [
        "include",
        "portable/Compiler/CCS",
        "../../../../../app/main/include",
        "../../../../../app/task/os",
    ]
    includes_win.extend(bld.env.FOXBMS_INCLUDES_RTOS_KERNEL)

    if bld.env.FOXBMS_UART_SUPPORT:
        includes_win.append("../../../../../app/driver/uart")

    source = "FreeRTOS_TCP_WIN"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS + ["--diag_suppress=179"],
        target=f"{op}{source}",
        idx=1,
    )

    # All other source files require the same includes and flags
    includes = [
        "include",
        "portable/Compiler/CCS",
        "../../../../../app/driver/phy",
        "../../../../../app/driver/emac",
        "../../../../../app/driver/config",
        "../../../../../app/driver/foxmath",
        "../../../../../app/driver/mcu",
        "../../../../../app/engine/database",
        "../../../../../app/engine/config",
        "../../../../../app/application/config",
        "../../../../../app/main/include",
        "../../../../../app/task/os",
    ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL

    if bld.env.FOXBMS_UART_SUPPORT:
        includes.append("../../../../../app/driver/uart")

    source = "FreeRTOS_ARP"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_BitConfig"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_DHCP"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_DHCPv6"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_DNS"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_DNS_Cache"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_DNS_Callback"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_DNS_Networking"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_DNS_Parser"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_ICMP"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_IP"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_IP_Timers"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_IP_Utils"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_IPv4"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_IPv4_Sockets"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_IPv4_Utils"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_IPv6"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_IPv6_Sockets"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_IPv6_Utils"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_ND"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_RA"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_Routing"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_Sockets"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_Stream_Buffer"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_TCP_IP"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_TCP_IP_IPv4"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_TCP_IP_IPv6"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_TCP_Reception"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_TCP_State_Handling"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_TCP_State_Handling_IPv4"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_TCP_State_Handling_IPv6"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_TCP_Transmission"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_TCP_Transmission_IPv4"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_TCP_Transmission_IPv6"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_TCP_Utils"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_TCP_Utils_IPv4"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_TCP_Utils_IPv6"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_Tiny_TCP"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_UDP_IP"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_UDP_IPv4"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "FreeRTOS_UDP_IPv6"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )
    source = "trace_macros"
    bld.objects(
        source=f"{source}.c",
        includes=includes_win,
        cflags=bld.env.CFLAGS_OS,
        target=f"{op}{source}",
        idx=1,
    )

    use = [
        f"{op}BufferAllocation_1",
        f"{op}NetworkInterface",
        f"{op}FreeRTOS_TCP_WIN",
        f"{op}FreeRTOS_ARP",
        f"{op}FreeRTOS_BitConfig",
        f"{op}FreeRTOS_DHCP",
        f"{op}FreeRTOS_DHCPv6",
        f"{op}FreeRTOS_DNS",
        f"{op}FreeRTOS_DNS_Cache",
        f"{op}FreeRTOS_DNS_Callback",
        f"{op}FreeRTOS_DNS_Networking",
        f"{op}FreeRTOS_DNS_Parser",
        f"{op}FreeRTOS_ICMP",
        f"{op}FreeRTOS_IP",
        f"{op}FreeRTOS_IP_Timers",
        f"{op}FreeRTOS_IP_Utils",
        f"{op}FreeRTOS_IPv4",
        f"{op}FreeRTOS_IPv4_Sockets",
        f"{op}FreeRTOS_IPv4_Utils",
        f"{op}FreeRTOS_IPv6",
        f"{op}FreeRTOS_IPv6_Sockets",
        f"{op}FreeRTOS_IPv6_Utils",
        f"{op}FreeRTOS_ND",
        f"{op}FreeRTOS_RA",
        f"{op}FreeRTOS_Routing",
        f"{op}FreeRTOS_Sockets",
        f"{op}FreeRTOS_Stream_Buffer",
        f"{op}FreeRTOS_TCP_IP",
        f"{op}FreeRTOS_TCP_IP_IPv4",
        f"{op}FreeRTOS_TCP_IP_IPv6",
        f"{op}FreeRTOS_TCP_Reception",
        f"{op}FreeRTOS_TCP_State_Handling",
        f"{op}FreeRTOS_TCP_State_Handling_IPv4",
        f"{op}FreeRTOS_TCP_State_Handling_IPv6",
        f"{op}FreeRTOS_TCP_Transmission",
        f"{op}FreeRTOS_TCP_Transmission_IPv4",
        f"{op}FreeRTOS_TCP_Transmission_IPv6",
        f"{op}FreeRTOS_TCP_Utils",
        f"{op}FreeRTOS_TCP_Utils_IPv4",
        f"{op}FreeRTOS_TCP_Utils_IPv6",
        f"{op}FreeRTOS_Tiny_TCP",
        f"{op}FreeRTOS_UDP_IP",
        f"{op}FreeRTOS_UDP_IPv4",
        f"{op}FreeRTOS_UDP_IPv6",
        f"{op}trace_macros",
        f"{lp}os",
    ]

    bld(
        features="c cstlib",
        use=use,
        target=f"{lp}tcp",
    )
