#!/usr/bin/env python3
#
# Copyright (c) 2010 - 2026, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"


from waflib.Build import BuildContext


def build(bld: BuildContext) -> None:
    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/application/ethernet/ethernet.c"),
            bld.path.find_node("test_ethernet.c"),
        ],
        target="test-app-ethernet",
        includes=[
            bld.srcnode.find_node("src/app/application/ethernet"),
            bld.srcnode.find_node("src/app/application/config"),
            bld.srcnode.find_node("src/app/driver/phy"),
            bld.srcnode.find_node("src/app/driver/emac"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/foxmath"),
            bld.srcnode.find_node("src/app/driver/uart"),
            bld.srcnode.find_node(
                "src/os/freertos/freertos-plus/freertos-plus-tcp/source/include"
            ),
            bld.srcnode.find_node(
                "src/os/freertos/freertos-plus/freertos-plus-tcp/source/portable/Compiler/CCS"
            ),
            bld.srcnode.find_node(
                "src/os/freertos/freertos-plus/freertos-plus-tcp/source/portable/"
                "NetworkInterface/tms570lc435"
            ),
        ],
        mocks=[
            bld.srcnode.find_node(
                "src/os/freertos/freertos-plus/freertos-plus-tcp/source/include/FreeRTOS_Routing.h"
            ),
            bld.srcnode.find_node(
                "src/os/freertos/freertos-plus/freertos-plus-tcp/source/include/FreeRTOS_Sockets.h"
            ),
            bld.srcnode.find_node(
                "src/os/freertos/freertos-plus/freertos-plus-tcp/source/include/NetworkInterface.h"
            ),
            bld.srcnode.find_node(
                "src/os/freertos/freertos-plus/freertos-plus-tcp/source/portable/"
                "NetworkInterface/tms570lc435/NetworkInterface_custom.h"
            ),
            bld.srcnode.find_node("src/app/application/config/ethernet_cfg.h"),
            bld.srcnode.find_node("src/app/application/ethernet/ethernet_freertos.h"),
            bld.srcnode.find_node("src/app/main/include/infinite-loop-helper.h"),
            bld.srcnode.find_node("src/os/freertos/freertos/include/mpu_prototypes.h"),
            bld.srcnode.find_node("src/app/task/os/os.h"),
            bld.srcnode.find_node("src/app/driver/foxmath/utils.h"),
        ],
        defines=[
            "FOXBMS_TCP_SUPPORT=1",
            "FOXBMS_UART_SUPPORT=1",
        ],
        cflags=[
            "-I",
            "../../src/os/freertos/freertos/include",
            "-include",
            "FreeRTOSConfig.h",
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/application/ethernet/ethernet_freertos.c"),
            bld.path.find_node("test_ethernet_freertos.c"),
        ],
        target="test-app-ethernet_freertos",
        includes=[
            bld.srcnode.find_node("src/app/application/ethernet"),
            bld.srcnode.find_node(
                "src/os/freertos/freertos-plus/freertos-plus-tcp/source/include"
            ),
            bld.srcnode.find_node(
                "src/os/freertos/freertos-plus/freertos-plus-tcp/source/portable/Compiler/CCS"
            ),
        ],
        mocks=[
            bld.srcnode.find_node(
                "src/os/freertos/freertos-plus/freertos-plus-tcp/source/include/FreeRTOS_Routing.h"
            ),
            bld.srcnode.find_node(
                "src/os/freertos/freertos-plus/freertos-plus-tcp/source/include/FreeRTOS_Sockets.h"
            ),
            bld.srcnode.find_node("src/os/freertos/freertos/include/mpu_prototypes.h"),
            bld.srcnode.find_node("src/app/task/os/os.h"),
        ],
        cflags=[
            "-I",
            "../../src/os/freertos/freertos/include",
            "-include",
            "FreeRTOSConfig.h",
        ],
    )
