#!/usr/bin/env python3
#
# Copyright (c) 2010 - 2026, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"


def build(bld):
    op = f"{bld.env.APPNAME.lower()}-object-"

    includes = [
        ".",
        "..",
        "../../../can",
        "../../../config",
        "../../../contactor",
        "../../../fram",
        "../../../sps",
        "../../../mcu",
        "../../../../application/bms",
        "../../../../application/config",
        "../../../../engine/config",
        "../../../../engine/database",
        "../../../../engine/diag",
        "../../../../engine/sys_mon",
        "../../../../main/include",
        "../../../../task/config",
        "../../../../task/os",
    ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
    source = "can_cbs_tx_f_bms-state-details"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        cflags=bld.env.CFLAGS_FOXBMS,
        target=f"{op}{source}",
        idx=1,
    )

    includes = [
        ".",
        "..",
        "../../../can",
        "../../../config",
        "../../../contactor",
        "../../../fram",
        "../../../foxmath",
        "../../../sps",
        "../../../mcu",
        "../../../../application/bms",
        "../../../../application/config",
        "../../../../engine/config",
        "../../../../engine/database",
        "../../../../engine/diag",
        "../../../../engine/sys_mon",
        "../../../../main/include",
        "../../../../task/config",
        "../../../../task/os",
    ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
    source = "can_cbs_tx_f_bms-state"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        cflags=bld.env.CFLAGS_FOXBMS,
        target=f"{op}{source}",
        idx=1,
    )

    includes = [
        ".",
        "..",
        "../../../can",
        "../../../config",
        "../../../foxmath",
        "../../../mcu",
        "../../../../application/config",
        "../../../../engine/config",
        "../../../../engine/database",
        "../../../../engine/diag",
        "../../../../engine/sys_mon",
        "../../../../main/include",
        "../../../../task/config",
        "../../../../task/os",
    ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
    source = "can_cbs_tx_f_cell-temperatures"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        cflags=bld.env.CFLAGS_FOXBMS,
        target=f"{op}{source}",
        idx=1,
    )

    includes = [
        ".",
        "..",
        "../../../can",
        "../../../config",
        "../../../foxmath",
        "../../../mcu",
        "../../../../application/config",
        "../../../../engine/config",
        "../../../../engine/database",
        "../../../../engine/diag",
        "../../../../engine/sys_mon",
        "../../../../main/include",
        "../../../../task/config",
        "../../../../task/os",
    ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
    source = "can_cbs_tx_f_cell-voltages"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        cflags=bld.env.CFLAGS_FOXBMS,
        target=f"{op}{source}",
        idx=1,
    )

    includes = [
        ".",
        "..",
        "../../../can",
        "../../../config",
        "../../../foxmath",
        "../../../mcu",
        "../../../../application/config",
        "../../../../engine/config",
        "../../../../engine/database",
        "../../../../main/include",
        "../../../../task/config",
        "../../../../task/os",
    ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
    source = "can_cbs_tx_f_pack-limits"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        cflags=bld.env.CFLAGS_FOXBMS,
        target=f"{op}{source}",
        idx=1,
    )

    includes = [
        ".",
        "..",
        "../../../can",
        "../../../config",
        "../../../contactor",
        "../../../foxmath",
        "../../../sps",
        "../../../mcu",
        "../../../../application/bms",
        "../../../../application/config",
        "../../../../engine/config",
        "../../../../engine/database",
        "../../../../main/include",
        "../../../../task/config",
        "../../../../task/os",
    ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
    source = "can_cbs_tx_f_pack-minimum-maximum-values"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        cflags=bld.env.CFLAGS_FOXBMS,
        target=f"{op}{source}",
        idx=1,
    )

    includes = [
        ".",
        "..",
        "../../../can",
        "../../../config",
        "../../../contactor",
        "../../../foxmath",
        "../../../sps",
        "../../../mcu",
        "../../../../application/bms",
        "../../../../application/config",
        "../../../../engine/config",
        "../../../../engine/database",
        "../../../../main/include",
        "../../../../task/config",
        "../../../../task/os",
    ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
    source = "can_cbs_tx_f_pack-state-estimation"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        cflags=bld.env.CFLAGS_FOXBMS,
        target=f"{op}{source}",
        idx=1,
    )

    includes = [
        ".",
        "..",
        "../../../can",
        "../../../config",
        "../../../foxmath",
        "../../../mcu",
        "../../../../application/bms",
        "../../../../application/config",
        "../../../../engine/config",
        "../../../../engine/database",
        "../../../../main/include",
        "../../../../task/config",
        "../../../../task/os",
    ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
    source = "can_cbs_tx_f_pack-values-p0"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        cflags=bld.env.CFLAGS_FOXBMS,
        target=f"{op}{source}",
        idx=1,
    )

    includes = [
        ".",
        "..",
        "../../../can",
        "../../../config",
        "../../../foxmath",
        "../../../mcu",
        "../../../../application/bms",
        "../../../../application/config",
        "../../../../engine/config",
        "../../../../engine/database",
        "../../../../main/include",
        "../../../../task/config",
        "../../../../task/os",
    ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
    source = "can_cbs_tx_f_pack-values-p1"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        cflags=bld.env.CFLAGS_FOXBMS,
        target=f"{op}{source}",
        idx=1,
    )

    includes = [
        ".",
        "..",
        "../../../can",
        "../../../config",
        "../../../contactor",
        "../../../foxmath",
        "../../../sps",
        "../../../mcu",
        "../../../../application/bms",
        "../../../../application/config",
        "../../../../engine/config",
        "../../../../engine/database",
        "../../../../main/include",
        "../../../../task/config",
        "../../../../task/os",
    ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
    source = "can_cbs_tx_f_string-minimum-maximum-values"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        cflags=bld.env.CFLAGS_FOXBMS,
        target=f"{op}{source}",
        idx=1,
    )

    includes = [
        ".",
        "..",
        "../../../can",
        "../../../config",
        "../../../contactor",
        "../../../foxmath",
        "../../../sps",
        "../../../mcu",
        "../../../../application/bms",
        "../../../../application/config",
        "../../../../engine/config",
        "../../../../engine/database",
        "../../../../main/include",
        "../../../../task/config",
        "../../../../task/os",
    ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
    source = "can_cbs_tx_f_string-state-estimation"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        cflags=bld.env.CFLAGS_FOXBMS,
        target=f"{op}{source}",
        idx=1,
    )

    includes = [
        ".",
        "..",
        "../../../can",
        "../../../config",
        "../../../contactor",
        "../../../foxmath",
        "../../../sps",
        "../../../mcu",
        "../../../../application/bms",
        "../../../../application/config",
        "../../../../engine/config",
        "../../../../engine/database",
        "../../../../main/include",
        "../../../../task/config",
        "../../../../task/os",
    ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
    source = "can_cbs_tx_f_string-state"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        cflags=bld.env.CFLAGS_FOXBMS,
        target=f"{op}{source}",
        idx=1,
    )

    includes = [
        ".",
        "..",
        "../../../can",
        "../../../config",
        "../../../foxmath",
        "../../../mcu",
        "../../../../application/bms",
        "../../../../application/config",
        "../../../../engine/config",
        "../../../../engine/database",
        "../../../../main/include",
        "../../../../task/config",
        "../../../../task/os",
    ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
    source = "can_cbs_tx_f_string-values-p0"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        cflags=bld.env.CFLAGS_FOXBMS,
        target=f"{op}{source}",
        idx=1,
    )

    includes = [
        ".",
        "..",
        "../../../can",
        "../../../config",
        "../../../foxmath",
        "../../../mcu",
        "../../../../application/bms",
        "../../../../application/config",
        "../../../../engine/config",
        "../../../../engine/database",
        "../../../../main/include",
        "../../../../task/config",
        "../../../../task/os",
    ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
    source = "can_cbs_tx_f_string-values-p1"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        cflags=bld.env.CFLAGS_FOXBMS,
        target=f"{op}{source}",
        idx=1,
    )

    includes = [
        ".",
        "..",
        "../../../can",
        "../../../config",
        "../../../mcu",
        "../../../../application/bms",
        "../../../../application/config",
        "../../../../engine/config",
        "../../../../engine/database",
        "../../../../engine/diag",
        "../../../../engine/sys",
        "../../../../main/include",
        "../../../../task/config",
        "../../../../task/os",
    ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
    source = "can_cbs_tx_f_sys-state"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        cflags=bld.env.CFLAGS_FOXBMS,
        target=f"{op}{source}",
        idx=1,
    )
