#!/usr/bin/env python3
#
# Copyright (c) 2010 - 2026, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"

from waflib.Build import BuildContext


def build(bld: BuildContext) -> None:
    op = f"{bld.env.APPNAME.lower()}-object-"
    lp = f"{bld.env.APPNAME.lower()}-"
    ip = f"{bld.env.APPNAME.lower()}-incpath-"
    target = bld.env.APPNAME.lower()

    source = "fassert"
    bld.objects(
        source=f"{source}.c",
        includes=[bld.path.find_node("include")],
        uselib="FOXBMS",
        target=f"{op}{source}",
    )

    source = "fstartup"
    use = f"{lp}hal"
    bld.objects(
        source=f"{source}.c",
        includes=[bld.path.find_node("include")],
        use=use,
        uselib="FOXBMS",
        target=f"{op}{source}",
    )

    includes = [
        bld.path.find_node("include"),
        bld.srcnode.find_node("src/app/application/config"),
        bld.srcnode.find_node("src/app/driver/adc"),
        bld.srcnode.find_node("src/app/driver/config"),
        bld.srcnode.find_node("src/app/driver/contactor"),
        bld.srcnode.find_node("src/app/driver/dma"),
        bld.srcnode.find_node("src/app/driver/emac"),
        bld.srcnode.find_node("src/app/driver/foxmath"),
        bld.srcnode.find_node("src/app/driver/i2c"),
        bld.srcnode.find_node("src/app/driver/io"),
        bld.srcnode.find_node("src/app/driver/led"),
        bld.srcnode.find_node("src/app/driver/mcu"),
        bld.srcnode.find_node("src/app/driver/meas"),
        bld.srcnode.find_node("src/app/driver/pwm"),
        bld.srcnode.find_node("src/app/driver/spi"),
        bld.srcnode.find_node("src/app/driver/sps"),
        bld.srcnode.find_node("src/app/engine/config"),
        bld.srcnode.find_node("src/app/engine/database"),
        bld.srcnode.find_node("src/app/engine/diag"),
        bld.srcnode.find_node("src/app/engine/hw_info"),
        bld.srcnode.find_node("src/app/task/config"),
        bld.srcnode.find_node("src/app/task/os"),
        bld.srcnode.find_node("src/version"),
    ]

    if bld.env.FOXBMS_TCP_SUPPORT:
        includes.append(bld.srcnode.find_node("src/app/application/ethernet"))
    if bld.env.FOXBMS_UART_SUPPORT:
        includes.append(bld.srcnode.find_node("src/app/driver/uart"))

    use = [
        f"{op}fassert",
        f"{op}fstartup",
        f"{lp}application",
        f"{lp}driver",
        f"{lp}engine",
        f"{lp}task",
        f"{lp}os",
        f"{lp}hal",
        f"{lp}tcp",
        f"{ip}afe",
        f"{ip}rtos-kernel",
        "foxbms_config",
        "rtsv7R4_A_be_v3D16_eabi",
    ]
    if bld.env.FOXBMS_TCP_SUPPORT:
        use.append(f"{ip}rtos-tcp")

    linker_script_elf = bld.path.find_node("app.cmd")
    linker_script_hex = bld.path.find_node("app_hex.cmd")
    source = "main"
    bld(
        features="c cprogram",
        source=f"{source}.c",
        includes=includes,
        use=use,
        uselib="FOXBMS",
        linker_script=linker_script_elf,
        linker_script_hex=linker_script_hex,
        version=True,
        app_build_cfg=True,
        target=target,
    )
