#!/usr/bin/env python3
#
# Copyright (c) 2010 - 2026, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"


def build(bld):
    op = f"{bld.env.APPNAME.lower()}-object-"
    lp = f"{bld.env.APPNAME.lower()}-"
    target = bld.env.APPNAME.lower()

    cflags = bld.env.CFLAGS_FOXBMS
    source = "fassert"
    bld.objects(
        source=f"{source}.c",
        includes="include",
        cflags=cflags,
        target=f"{op}{source}",
        idx=1,
    )
    source = "fstartup"
    bld.objects(
        source=f"{source}.c",
        includes="include",
        cflags=cflags,
        target=f"{op}{source}",
        idx=1,
    )

    linker_script_elf = bld.path.find_node("app.cmd")
    linker_script_hex = bld.path.find_node("app_hex.cmd")
    includes = (
        [
            "include",
            "../application/config",
            "../driver/adc",
            "../driver/config",
            "../driver/contactor",
            "../driver/dma",
            "../driver/emac",
            "../driver/foxmath",
            "../driver/i2c",
            "../driver/io",
            "../driver/led",
            "../driver/meas",
            "../driver/pwm",
            "../driver/spi",
            "../driver/sps",
            "../driver/mcu",
            "../engine/config",
            "../engine/database",
            "../engine/diag",
            "../engine/hw_info",
            "../task/os",
            "../task/config",
            "../../version",
        ]
        + [
            bld.root.find_node(i).path_from(bld.path)
            for i in bld.env.FOXBMS_INCLUDES_AFE
        ]
        + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
        + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL_ADDONS
    )

    if bld.env.FOXBMS_TCP_SUPPORT:
        includes.append("../application/ethernet")
    if bld.env.FOXBMS_UART_SUPPORT:
        includes.append("../driver/uart")

    use = [
        f"{op}fassert",
        f"{op}fstartup",
        f"{lp}application",
        f"{lp}task",
        f"{lp}engine",
        f"{lp}driver",
        f"{lp}os",
        f"{lp}hal",
        f"{lp}tcp",
    ]
    source = "main"
    bld.tiprogram(
        source=f"{source}.c",
        linker_script=linker_script_elf,
        linker_script_hex=linker_script_hex,
        includes=includes,
        cflags=cflags,
        use=use,
        target=target,
        app_build_cfg=True,
        idx=1,
    )
