#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (c) 2010 - 2021, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"

"""TODO"""

import os


def build(bld):
    """builds the algorithm library"""
    soc = bld.env.ALGORITHM_SOC
    soe = bld.env.ALGORITHM_SOE
    soh = bld.env.ALGORITHM_SOH
    source = [
        os.path.join("algorithm.c"),
        os.path.join("config", "algorithm_cfg.c"),
        os.path.join("moving_average", "moving_average.c"),
        os.path.join("state_estimation", "soc", soc, f"soc_{soc}_cfg.c"),
        os.path.join("state_estimation", "soc", soc, f"soc_{soc}.c"),
        os.path.join("state_estimation", "soe", soe, f"soe_{soe}_cfg.c"),
        os.path.join("state_estimation", "soe", soe, f"soe_{soe}.c"),
        os.path.join("state_estimation", "soh", soh, f"soh_{soh}.c"),
        os.path.join(".", "state_estimation", "state_estimation.c"),
        os.path.join(".", "state_estimation", "sof", "trapezoid", "sof.c"),
        os.path.join(".", "state_estimation", "sof", "trapezoid", "sof_cfg.c"),
    ]
    includes = [
        ".",
        "config",
        "moving_average",
        "state_estimation",
        os.path.join("state_estimation", "soc", soc),
        os.path.join("state_estimation", "soe", soe),
        os.path.join("state_estimation", "soh", soh),
        os.path.join("state_estimation", "sof", "trapezoid"),
        os.path.join("..", "config"),
        os.path.join("..", "..", "application", "bms"),
        os.path.join("..", "..", "driver", "config"),
        os.path.join("..", "..", "driver", "contactor"),
        os.path.join("..", "..", "driver", "foxmath"),
        os.path.join("..", "..", "driver", "fram"),
        os.path.join("..", "..", "driver", "sps"),
        os.path.join("..", "..", "engine", "config"),
        os.path.join("..", "..", "engine", "database"),
        os.path.join("..", "..", "engine", "diag"),
        os.path.join("..", "..", "main", "include"),
        os.path.join("..", "..", "task", "config"),
        os.path.join("..", "..", "task", "os"),
    ]
    includes.extend(bld.env.INCLUDES_OPERATING_SYSTEM)
    cflags = bld.env.CFLAGS_FOXBMS
    target = f"{bld.env.APPNAME.lower()}-algorithms"
    bld.stlib(
        source=source,
        includes=includes,
        cflags=cflags,
        target=target,
    )
