#!/usr/bin/env python3
#
# Copyright (c) 2010 - 2026, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"

from waflib.Build import BuildContext


def build(bld: BuildContext) -> None:
    op = f"{bld.env.APPNAME.lower()}-object-"
    lp = f"{bld.env.APPNAME.lower()}-"
    ip = f"{bld.env.APPNAME.lower()}-incpath-"

    bld.recurse(["config", "moving_average", "state_estimation"])

    includes = [
        bld.path,
        bld.path.find_node("config"),
        bld.srcnode.find_node("src/app/main/include"),
        bld.srcnode.find_node("src/app/task/os"),
    ]
    use = [
        f"{lp}hal",
        f"{ip}rtos-kernel",
        "foxbms_config",
    ]
    source = "algorithm"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        use=use,
        uselib="FOXBMS",
        target=f"{op}{source}",
    )

    use = [
        f"{lp}hal",
        f"{op}algorithm",
        f"{op}algorithm_cfg",
        f"{op}moving_average",
        f"{op}state_estimation",
        f"{op}soc_{bld.env.FOXBMS_ALGORITHM_STATE_ESTIMATOR_SOC}",
        f"{op}soe_{bld.env.FOXBMS_ALGORITHM_STATE_ESTIMATOR_SOE}",
        f"{op}sof_{bld.env.FOXBMS_ALGORITHM_STATE_ESTIMATOR_SOF}",
        f"{op}sof_{bld.env.FOXBMS_ALGORITHM_STATE_ESTIMATOR_SOF}_cfg",
        f"{op}soh_{bld.env.FOXBMS_ALGORITHM_STATE_ESTIMATOR_SOH}",
    ]

    bld(
        features="c cstlib",
        use=use,
        target=f"{lp}algorithm",
    )
