#!/usr/bin/env python3
#
# Copyright (c) 2010 - 2026, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"

"""Add git version information to build artifacts."""

from datetime import UTC, datetime

from c_template import render_template
from misc_helpers import map_python_bool_to_c_bool

from vcs import VcsInformation
from waflib.Configure import ConfigurationContext, conf


VERSION_STRUCT_TEMPLATE = """const VER_VERSION_s ver_versionInformation VER_VERSION_INFORMATION = {{
    .underVersionControl = {under_version_control},
    .isDirty = {is_dirty},
    .major = {major}u,
    .minor = {minor}u,
    .patch = {patch}u,
    .distanceFromLastRelease = {distance}u,
    .commitHash = "{commit}",
    .remote = "{remote}",
}};
"""


@conf
def create_version_c(ctx: ConfigurationContext, txt: str) -> str:
    """Create the version source code from a template.

    Args:
        ctx : Waf ConfigurationContext Waf
        txt : Input C source template as string
        version : Git metadata containing version components and commit
            information.
        is_git_repo : C-boolean indicating whether the source is under version
            control.
        is_dirty : C-boolean  indicating whether the working tree is dirty.
        git_remote : The git remote URL or name.

    Returns:
        The generated C source code containing version information
    """
    version: VcsInformation = ctx.gather_and_validate_version_info()
    today = datetime.now(tz=UTC).date().strftime("%Y-%m-%d")

    version_block = VERSION_STRUCT_TEMPLATE.format(
        under_version_control=map_python_bool_to_c_bool(version.under_version_control),
        is_dirty=map_python_bool_to_c_bool(version.dirty),
        major=version.major,
        minor=version.minor,
        patch=version.patch,
        distance=version.distance,
        commit=version.short_hash,
        remote=version.remote,
    )

    includes = '#include "version.h"\n\n#include <stdbool.h>\n#include <stdint.h>'
    return render_template(
        txt,
        {
            "file_name": "version.c",
            "author": "foxBMS Team",
            "date": f"{today} (date of creation)",
            "updated": f"{today} (date of last update)",
            "version": f"v{version.major}.{version.minor}.{version.patch}",
            "ingroup": "GENERAL",
            "prefix": "VER",
            "brief": "Version information that is generated by the toolchain.",
            "details": "Version information that is generated by the toolchain.",
            "include_directives": includes,
            "static_constant_and_variable_definitions": version_block,
        },
    )
