#!/usr/bin/env python3
#
# Copyright (c) 2010 - 2026, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"


from waflib.Build import BuildContext


def build(bld: BuildContext) -> None:
    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/engine/diag/cbs/diag_cbs_aerosol-sensor.c"),
            bld.path.find_node("test_diag_cbs_aerosol-sensor.c"),
        ],
        target="test-app-diag_cbs_aerosol-sensor",
        includes=[
            bld.srcnode.find_node("src/app/engine/diag/cbs"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/engine/config/diag_cfg.h"),
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/engine/diag/cbs/diag_cbs_afe.c"),
            bld.path.find_node("test_diag_cbs_afe.c"),
        ],
        target="test-app-diag_cbs_afe",
        includes=[
            bld.srcnode.find_node("src/app/engine/diag/cbs"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/engine/config/diag_cfg.h"),
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/engine/diag/cbs/diag_cbs_bms.c"),
            bld.path.find_node("test_diag_cbs_bms.c"),
        ],
        target="test-app-diag_cbs_bms",
        includes=[
            bld.srcnode.find_node("src/app/engine/diag/cbs"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/engine/config/diag_cfg.h"),
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/engine/diag/cbs/diag_cbs_can.c"),
            bld.path.find_node("test_diag_cbs_can.c"),
        ],
        target="test-app-diag_cbs_can",
        includes=[
            bld.srcnode.find_node("src/app/engine/diag/cbs"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/engine/config/diag_cfg.h"),
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/engine/diag/cbs/diag_cbs_clamp30c.c"),
            bld.path.find_node("test_diag_cbs_clamp30c.c"),
        ],
        target="test-app-diag_cbs_clamp30c",
        includes=[
            bld.srcnode.find_node("src/app/engine/diag/cbs"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/engine/config/diag_cfg.h"),
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/engine/diag/cbs/diag_cbs_contactor.c"),
            bld.path.find_node("test_diag_cbs_contactor.c"),
        ],
        target="test-app-diag_cbs_contactor",
        includes=[
            bld.srcnode.find_node("src/app/engine/diag/cbs"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/engine/config/diag_cfg.h"),
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/engine/diag/cbs/diag_cbs_current-sensor.c"),
            bld.path.find_node("test_diag_cbs_current-sensor.c"),
        ],
        target="test-app-diag_cbs_current-sensor",
        includes=[
            bld.srcnode.find_node("src/app/engine/diag/cbs"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/engine/config/diag_cfg.h"),
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/engine/diag/cbs/diag_cbs_current.c"),
            bld.path.find_node("test_diag_cbs_current.c"),
        ],
        target="test-app-diag_cbs_current",
        includes=[
            bld.srcnode.find_node("src/app/engine/diag/cbs"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/engine/config/diag_cfg.h"),
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/engine/diag/cbs/diag_cbs_deep-discharge.c"),
            bld.srcnode.find_node("src/app/driver/config/fram_cfg.c"),
            bld.path.find_node("test_diag_cbs_deep-discharge.c"),
        ],
        target="test-app-diag_cbs_deep-discharge",
        includes=[
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/fram"),
            bld.srcnode.find_node("src/app/engine/diag/cbs"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/engine/config/diag_cfg.h"),
            bld.srcnode.find_node("src/app/driver/fram/fram.h"),
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/engine/diag/cbs/diag_cbs_dummy.c"),
            bld.path.find_node("test_diag_cbs_dummy.c"),
        ],
        target="test-app-diag_cbs_dummy",
        includes=[
            bld.srcnode.find_node("src/app/engine/diag/cbs"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/engine/config/diag_cfg.h"),
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/engine/diag/cbs/diag_cbs_fram.c"),
            bld.path.find_node("test_diag_cbs_fram.c"),
        ],
        target="test-app-diag_cbs_fram",
        includes=[
            bld.srcnode.find_node("src/app/engine/diag/cbs"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/engine/config/diag_cfg.h"),
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/engine/diag/cbs/diag_cbs_i2c.c"),
            bld.path.find_node("test_diag_cbs_i2c.c"),
        ],
        target="test-app-diag_cbs_i2c",
        includes=[
            bld.srcnode.find_node("src/app/engine/diag/cbs"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/engine/config/diag_cfg.h"),
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/engine/diag/cbs/diag_cbs_insulation.c"),
            bld.path.find_node("test_diag_cbs_insulation.c"),
        ],
        target="test-app-diag_cbs_insulation",
        includes=[
            bld.srcnode.find_node("src/app/engine/diag/cbs"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/engine/config/diag_cfg.h"),
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/engine/diag/cbs/diag_cbs_interlock.c"),
            bld.path.find_node("test_diag_cbs_interlock.c"),
        ],
        target="test-app-diag_cbs_interlock",
        includes=[
            bld.srcnode.find_node("src/app/engine/diag/cbs"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/engine/config/diag_cfg.h"),
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/engine/diag/cbs/diag_cbs_plausibility.c"),
            bld.path.find_node("test_diag_cbs_plausibility.c"),
        ],
        target="test-app-diag_cbs_plausibility",
        includes=[
            bld.srcnode.find_node("src/app/engine/diag/cbs"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/engine/config/diag_cfg.h"),
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node(
                "src/app/engine/diag/cbs/diag_cbs_power-measurement.c"
            ),
            bld.path.find_node("test_diag_cbs_power-measurement.c"),
        ],
        target="test-app-diag_cbs_power-measurement",
        includes=[
            bld.srcnode.find_node("src/app/engine/diag/cbs"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/engine/config/diag_cfg.h"),
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/engine/diag/cbs/diag_cbs_rtc.c"),
            bld.path.find_node("test_diag_cbs_rtc.c"),
        ],
        target="test-app-diag_cbs_rtc",
        includes=[
            bld.srcnode.find_node("src/app/engine/diag/cbs"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/engine/config/diag_cfg.h"),
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/engine/diag/cbs/diag_cbs_sbc.c"),
            bld.path.find_node("test_diag_cbs_sbc.c"),
        ],
        target="test-app-diag_cbs_sbc",
        includes=[
            bld.srcnode.find_node("src/app/engine/diag/cbs"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/engine/config/diag_cfg.h"),
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/engine/diag/cbs/diag_cbs_sys-mon.c"),
            bld.path.find_node("test_diag_cbs_sys-mon.c"),
        ],
        target="test-app-diag_cbs_sys-mon",
        includes=[
            bld.srcnode.find_node("src/app/engine/diag/cbs"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/engine/config/diag_cfg.h"),
            bld.srcnode.find_node("src/app/engine/config/sys_mon_cfg.h"),
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/engine/diag/cbs/diag_cbs_temperature.c"),
            bld.path.find_node("test_diag_cbs_temperature.c"),
        ],
        target="test-app-diag_cbs_temperature",
        includes=[
            bld.srcnode.find_node("src/app/engine/diag/cbs"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/engine/config/diag_cfg.h"),
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/engine/diag/cbs/diag_cbs_voltage.c"),
            bld.path.find_node("test_diag_cbs_voltage.c"),
        ],
        target="test-app-diag_cbs_voltage",
        includes=[
            bld.srcnode.find_node("src/app/engine/diag/cbs"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/engine/config/diag_cfg.h"),
        ],
    )
