#!/usr/bin/env python3
#
# Copyright (c) 2010 - 2026, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"


def build(bld):
    op = f"{bld.env.APPNAME.lower()}-object-"

    includes = [
        ".",
        "..",
        "../../../config",
        "../../../fram",
        "../../../mcu",
        "../../../../application/bal",
        "../../../../application/config",
        "../../../../engine/config",
        "../../../../engine/database",
        "../../../../engine/diag",
        "../../../../engine/sys_mon",
        "../../../../main/include",
        "../../../../task/config",
        "../../../../task/os",
    ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
    source = "can_cbs_rx_f_bms-state-request"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        cflags=bld.env.CFLAGS_FOXBMS,
        target=f"{op}{source}",
        idx=1,
    )

    includes = [
        ".",
        "..",
        "../tx-async",
        "../../../config",
        "../../../afe/api",
        "../../../rtc",
        "../../../fram",
        "../../../mcu",
        "../../../../application/config",
        "../../../../engine/config",
        "../../../../engine/database",
        "../../../../engine/sys",
        "../../../../main/include",
        "../../../../task/config",
        "../../../../task/ftask",
        "../../../../task/os",
    ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
    source = "can_cbs_rx_f_debug"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        cflags=bld.env.CFLAGS_FOXBMS,
        target=f"{op}{source}",
        idx=1,
    )

    if bld.is_aerosol_sensor_honeywell_bas6c_x00():
        includes = [
            ".",
            "..",
            "../../../config",
            "../../../mcu",
            "../../../../application/config",
            "../../../../engine/config",
            "../../../../engine/database",
            "../../../../engine/diag",
            "../../../../main/include",
            "../../../../task/os",
        ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
        source = "can_cbs_rx_as_honeywell-bas6c-x00"
        bld.objects(
            source=f"{source}.c",
            includes=includes,
            cflags=bld.env.CFLAGS_FOXBMS,
            target=f"{op}{source}",
            idx=1,
        )

    if bld.is_bms_slave_debug_can():
        includes = [
            ".",
            "..",
            "../../../config",
            "../../../rtc",
            "../../../mcu",
            "../../../../application/config",
            "../../../../engine/config",
            "../../../../engine/database",
            "../../../../engine/diag",
            "../../../../main/include",
            "../../../../task/config",
            "../../../../task/os",
            "../../../../task/ftask",
        ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
        source = "can_cbs_rx_afe_cell-temperatures"
        bld.objects(
            source=f"{source}.c",
            includes=includes,
            cflags=bld.env.CFLAGS_FOXBMS,
            target=f"{op}{source}",
            idx=1,
        )

        includes = [
            ".",
            "..",
            "../../../config",
            "../../../rtc",
            "../../../mcu",
            "../../../../application/config",
            "../../../../engine/config",
            "../../../../engine/database",
            "../../../../engine/diag",
            "../../../../main/include",
            "../../../../task/config",
            "../../../../task/os",
            "../../../../task/ftask",
        ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
        source = "can_cbs_rx_afe_cell-voltages"
        bld.objects(
            source=f"{source}.c",
            includes=includes,
            cflags=bld.env.CFLAGS_FOXBMS,
            target=f"{op}{source}",
            idx=1,
        )

    if bld.is_current_sensor_lem_cab500():
        includes = [
            ".",
            "..",
            "../../../config",
            "../../../mcu",
            "../../../../application/config",
            "../../../../engine/config",
            "../../../../engine/database",
            "../../../../main/include",
            "../../../../task/os",
        ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
        source = "can_cbs_rx_cs_lem-cab500"
        bld.objects(
            source=f"{source}.c",
            includes=includes,
            cflags=bld.env.CFLAGS_FOXBMS,
            target=f"{op}{source}",
            idx=1,
        )

    if bld.is_imd_bender_iso165c():
        includes = [
            ".",
            "..",
            "../../../config",
            "../../../mcu",
            "../../../foxmath",
            "../../../imd",
            "../../../imd/bender/iso165c",
            "../../../imd/bender/iso165c/config",
            "../../../../application/config",
            "../../../../engine/config",
            "../../../../engine/database",
            "../../../../main/include",
            "../../../../task/config",
            "../../../../task/os",
        ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
        source = "can_cbs_rx_imd_bender-iso165c-info"
        bld.objects(
            source=f"{source}.c",
            includes=includes,
            cflags=bld.env.CFLAGS_FOXBMS,
            target=f"{op}{source}",
            idx=1,
        )
        includes = [
            ".",
            "..",
            "../../../config",
            "../../../mcu",
            "../../../foxmath",
            "../../../imd",
            "../../../imd/bender/iso165c",
            "../../../imd/bender/iso165c/config",
            "../../../../application/config",
            "../../../../engine/config",
            "../../../../engine/database",
            "../../../../main/include",
            "../../../../task/config",
            "../../../../task/os",
        ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
        source = "can_cbs_rx_imd_bender-iso165c-response"
        bld.objects(
            source=f"{source}.c",
            includes=includes,
            cflags=bld.env.CFLAGS_FOXBMS,
            target=f"{op}{source}",
            idx=1,
        )

    if bld.is_current_sensor_isabellenhuette_ivt_s():
        includes = [
            ".",
            "..",
            "../../../config",
            "../../../mcu",
            "../../../foxmath",
            "../../../imd",
            "../../../imd/bender/iso165c",
            "../../../imd/bender/iso165c/config",
            "../../../../application/config",
            "../../../../engine/config",
            "../../../../engine/database",
            "../../../../main/include",
            "../../../../task/config",
            "../../../../task/os",
        ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
        source = "can_cbs_rx_cs_isabellenhuette-ivt-s"
        bld.objects(
            source=f"{source}.c",
            includes=includes,
            cflags=bld.env.CFLAGS_FOXBMS,
            target=f"{op}{source}",
            idx=1,
        )
