#!/usr/bin/env python3
#
# Copyright (c) 2010 - 2026, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"

from waflib.Build import BuildContext


def build(bld: BuildContext) -> None:
    op = f"{bld.env.APPNAME.lower()}-object-"
    lp = f"{bld.env.APPNAME.lower()}-"
    ip = f"{bld.env.APPNAME.lower()}-incpath-"
    cp = f"{bld.env.APPNAME.lower()}-config-"

    use = [
        f"{lp}hal",
        f"{ip}rtos-kernel",
        f"{cp}battery_system_cfg",
        "foxbms_config",
    ]

    includes = [
        bld.path,
        bld.srcnode.find_node("src/app/application/bal"),
        bld.srcnode.find_node("src/app/application/config"),
        bld.srcnode.find_node("src/app/driver/can/cbs"),
        bld.srcnode.find_node("src/app/driver/config"),
        bld.srcnode.find_node("src/app/driver/fram"),
        bld.srcnode.find_node("src/app/driver/mcu"),
        bld.srcnode.find_node("src/app/engine/config"),
        bld.srcnode.find_node("src/app/engine/database"),
        bld.srcnode.find_node("src/app/engine/diag"),
        bld.srcnode.find_node("src/app/engine/sys_mon"),
        bld.srcnode.find_node("src/app/main/include"),
        bld.srcnode.find_node("src/app/task/config"),
        bld.srcnode.find_node("src/app/task/os"),
    ]
    source = "can_cbs_rx_f_bms-state-request"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        use=use,
        uselib="FOXBMS",
        target=f"{op}{source}",
    )

    includes = [
        bld.path,
        bld.srcnode.find_node("src/app/application/config"),
        bld.srcnode.find_node("src/app/driver/afe/api"),
        bld.srcnode.find_node("src/app/driver/can/cbs"),
        bld.srcnode.find_node("src/app/driver/can/cbs/tx-async"),
        bld.srcnode.find_node("src/app/driver/config"),
        bld.srcnode.find_node("src/app/driver/fram"),
        bld.srcnode.find_node("src/app/driver/mcu"),
        bld.srcnode.find_node("src/app/driver/rtc"),
        bld.srcnode.find_node("src/app/engine/config"),
        bld.srcnode.find_node("src/app/engine/database"),
        bld.srcnode.find_node("src/app/engine/sys"),
        bld.srcnode.find_node("src/app/main/include"),
        bld.srcnode.find_node("src/app/task/config"),
        bld.srcnode.find_node("src/app/task/ftask"),
        bld.srcnode.find_node("src/app/task/os"),
    ]
    source = "can_cbs_rx_f_debug"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        use=use,
        uselib="FOXBMS",
        target=f"{op}{source}",
    )

    if bld.is_aerosol_sensor_honeywell_bas6c_x00():
        includes = [
            bld.path,
            bld.srcnode.find_node("src/app/application/config"),
            bld.srcnode.find_node("src/app/driver/can/cbs"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/mcu"),
            bld.srcnode.find_node("src/app/engine/config"),
            bld.srcnode.find_node("src/app/engine/database"),
            bld.srcnode.find_node("src/app/engine/diag"),
            bld.srcnode.find_node("src/app/main/include"),
            bld.srcnode.find_node("src/app/task/os"),
        ]
        source = "can_cbs_rx_as_honeywell-bas6c-x00"
        bld.objects(
            source=f"{source}.c",
            includes=includes,
            use=use,
            uselib="FOXBMS",
            target=f"{op}{source}",
        )

    if bld.is_bms_slave_debug_can():
        includes = [
            bld.path,
            bld.srcnode.find_node("src/app/application/config"),
            bld.srcnode.find_node("src/app/driver/can/cbs"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/fram"),
            bld.srcnode.find_node("src/app/driver/mcu"),
            bld.srcnode.find_node("src/app/driver/rtc"),
            bld.srcnode.find_node("src/app/engine/config"),
            bld.srcnode.find_node("src/app/engine/database"),
            bld.srcnode.find_node("src/app/engine/diag"),
            bld.srcnode.find_node("src/app/main/include"),
            bld.srcnode.find_node("src/app/task/config"),
            bld.srcnode.find_node("src/app/task/ftask"),
            bld.srcnode.find_node("src/app/task/os"),
        ]
        source = "can_cbs_rx_afe_cell-temperatures"
        bld.objects(
            source=f"{source}.c",
            includes=includes,
            use=use,
            uselib="FOXBMS",
            target=f"{op}{source}",
        )

        includes = [
            bld.path,
            bld.srcnode.find_node("src/app/application/config"),
            bld.srcnode.find_node("src/app/driver/can/cbs"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/fram"),
            bld.srcnode.find_node("src/app/driver/mcu"),
            bld.srcnode.find_node("src/app/driver/rtc"),
            bld.srcnode.find_node("src/app/engine/config"),
            bld.srcnode.find_node("src/app/engine/database"),
            bld.srcnode.find_node("src/app/engine/diag"),
            bld.srcnode.find_node("src/app/main/include"),
            bld.srcnode.find_node("src/app/task/config"),
            bld.srcnode.find_node("src/app/task/ftask"),
            bld.srcnode.find_node("src/app/task/os"),
        ]
        source = "can_cbs_rx_afe_cell-voltages"
        bld.objects(
            source=f"{source}.c",
            includes=includes,
            use=use,
            uselib="FOXBMS",
            target=f"{op}{source}",
        )

    if bld.is_current_sensor_lem_cab500():
        includes = [
            bld.path,
            bld.srcnode.find_node("src/app/application/config"),
            bld.srcnode.find_node("src/app/driver/can/cbs"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/fram"),
            bld.srcnode.find_node("src/app/driver/mcu"),
            bld.srcnode.find_node("src/app/engine/config"),
            bld.srcnode.find_node("src/app/engine/database"),
            bld.srcnode.find_node("src/app/main/include"),
            bld.srcnode.find_node("src/app/task/os"),
        ]
        source = "can_cbs_rx_cs_lem-cab500"
        bld.objects(
            source=f"{source}.c",
            includes=includes,
            use=use,
            uselib="FOXBMS",
            target=f"{op}{source}",
        )

    if bld.is_imd_bender_iso165c():
        use.append(f"{ip}imd-bender_iso165c")
        includes = [
            bld.path,
            bld.srcnode.find_node("src/app/application/config"),
            bld.srcnode.find_node("src/app/driver/can/cbs"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/foxmath"),
            bld.srcnode.find_node("src/app/driver/fram"),
            bld.srcnode.find_node("src/app/driver/imd"),
            bld.srcnode.find_node("src/app/driver/mcu"),
            bld.srcnode.find_node("src/app/engine/config"),
            bld.srcnode.find_node("src/app/engine/database"),
            bld.srcnode.find_node("src/app/main/include"),
            bld.srcnode.find_node("src/app/task/config"),
            bld.srcnode.find_node("src/app/task/os"),
        ]
        source = "can_cbs_rx_imd_bender-iso165c-info"
        bld.objects(
            source=f"{source}.c",
            includes=includes,
            use=use,
            uselib="FOXBMS",
            target=f"{op}{source}",
        )
        includes = [
            bld.path,
            bld.srcnode.find_node("src/app/application/config"),
            bld.srcnode.find_node("src/app/driver/can/cbs"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/foxmath"),
            bld.srcnode.find_node("src/app/driver/fram"),
            bld.srcnode.find_node("src/app/driver/imd"),
            bld.srcnode.find_node("src/app/driver/mcu"),
            bld.srcnode.find_node("src/app/engine/config"),
            bld.srcnode.find_node("src/app/engine/database"),
            bld.srcnode.find_node("src/app/main/include"),
            bld.srcnode.find_node("src/app/task/config"),
            bld.srcnode.find_node("src/app/task/os"),
        ]
        source = "can_cbs_rx_imd_bender-iso165c-response"
        bld.objects(
            source=f"{source}.c",
            includes=includes,
            use=use,
            uselib="FOXBMS",
            target=f"{op}{source}",
        )

    if bld.is_current_sensor_isabellenhuette_ivt_s():
        includes = [
            bld.path,
            bld.srcnode.find_node("src/app/application/config"),
            bld.srcnode.find_node("src/app/driver/can/cbs"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/foxmath"),
            bld.srcnode.find_node("src/app/driver/fram"),
            bld.srcnode.find_node("src/app/driver/imd"),
            bld.srcnode.find_node("src/app/driver/mcu"),
            bld.srcnode.find_node("src/app/engine/config"),
            bld.srcnode.find_node("src/app/engine/database"),
            bld.srcnode.find_node("src/app/main/include"),
            bld.srcnode.find_node("src/app/task/config"),
            bld.srcnode.find_node("src/app/task/os"),
        ]
        source = "can_cbs_rx_cs_isabellenhuette-ivt-s"
        bld.objects(
            source=f"{source}.c",
            includes=includes,
            use=use,
            uselib="FOXBMS",
            target=f"{op}{source}",
        )
