#!/usr/bin/env python3
#
# Copyright (c) 2010 - 2026, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"


from waflib.Build import BuildContext


def build(bld: BuildContext) -> None:
    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/driver/spi/spi.c"),
            bld.path.find_node("test_spi_adi.c"),
        ],
        target="test-app-spi_adi",
        includes=[
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/dma"),
            bld.srcnode.find_node("src/app/driver/io"),
            bld.srcnode.find_node("src/app/driver/spi"),
        ],
        mocks=[
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_spi.h"),
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_sys_dma.h"),
            bld.srcnode.find_node("src/app/driver/config/dma_cfg.h"),
            bld.srcnode.find_node("src/app/driver/io/io.h"),
            bld.srcnode.find_node("src/app/driver/mcu/mcu.h"),
            bld.srcnode.find_node("src/app/task/os/os.h"),
            bld.srcnode.find_node("src/app/driver/config/spi_cfg.h"),
            bld.srcnode.find_node("src/app/driver/config/spi_cfg_initialization.h"),
        ],
        defines=[
            "FOXBMS_AFE_DRIVER_ADI=1u",
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/driver/spi/spi.c"),
            bld.path.find_node("test_spi_debug.c"),
        ],
        target="test-app-spi_debug",
        includes=[
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/dma"),
            bld.srcnode.find_node("src/app/driver/io"),
            bld.srcnode.find_node("src/app/driver/spi"),
        ],
        mocks=[
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_spi.h"),
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_sys_dma.h"),
            bld.srcnode.find_node("src/app/driver/config/dma_cfg.h"),
            bld.srcnode.find_node("src/app/driver/io/io.h"),
            bld.srcnode.find_node("src/app/driver/mcu/mcu.h"),
            bld.srcnode.find_node("src/app/task/os/os.h"),
            bld.srcnode.find_node("src/app/driver/config/spi_cfg.h"),
            bld.srcnode.find_node("src/app/driver/config/spi_cfg_initialization.h"),
        ],
        defines=[
            "FOXBMS_AFE_DRIVER_DEBUG=1u",
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/driver/spi/spi.c"),
            bld.path.find_node("test_spi_ltc.c"),
        ],
        target="test-app-spi_ltc",
        includes=[
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/dma"),
            bld.srcnode.find_node("src/app/driver/io"),
            bld.srcnode.find_node("src/app/driver/spi"),
        ],
        mocks=[
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_spi.h"),
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_sys_dma.h"),
            bld.srcnode.find_node("src/app/driver/config/dma_cfg.h"),
            bld.srcnode.find_node("src/app/driver/io/io.h"),
            bld.srcnode.find_node("src/app/driver/mcu/mcu.h"),
            bld.srcnode.find_node("src/app/task/os/os.h"),
            bld.srcnode.find_node("src/app/driver/config/spi_cfg.h"),
            bld.srcnode.find_node("src/app/driver/config/spi_cfg_initialization.h"),
        ],
        defines=[
            "FOXBMS_AFE_DRIVER_LTC=1u",
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/driver/spi/spi.c"),
            bld.path.find_node("test_spi_mxm.c"),
        ],
        target="test-app-spi_mxm",
        includes=[
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/dma"),
            bld.srcnode.find_node("src/app/driver/io"),
            bld.srcnode.find_node("src/app/driver/spi"),
        ],
        mocks=[
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_spi.h"),
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_sys_dma.h"),
            bld.srcnode.find_node("src/app/driver/config/dma_cfg.h"),
            bld.srcnode.find_node("src/app/driver/io/io.h"),
            bld.srcnode.find_node("src/app/driver/mcu/mcu.h"),
            bld.srcnode.find_node("src/app/task/os/os.h"),
            bld.srcnode.find_node("src/app/driver/config/spi_cfg.h"),
            bld.srcnode.find_node("src/app/driver/config/spi_cfg_initialization.h"),
        ],
        defines=[
            "FOXBMS_AFE_DRIVER_MAXIM=1u",
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/driver/spi/spi.c"),
            bld.path.find_node("test_spi_nxp.c"),
        ],
        target="test-app-spi_nxp",
        includes=[
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/dma"),
            bld.srcnode.find_node("src/app/driver/io"),
            bld.srcnode.find_node("src/app/driver/spi"),
        ],
        mocks=[
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_spi.h"),
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_sys_dma.h"),
            bld.srcnode.find_node("src/app/driver/config/dma_cfg.h"),
            bld.srcnode.find_node("src/app/driver/io/io.h"),
            bld.srcnode.find_node("src/app/driver/mcu/mcu.h"),
            bld.srcnode.find_node("src/app/task/os/os.h"),
            bld.srcnode.find_node("src/app/driver/config/spi_cfg.h"),
            bld.srcnode.find_node("src/app/driver/config/spi_cfg_initialization.h"),
        ],
        defines=[
            "FOXBMS_AFE_DRIVER_NXP=1u",
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/driver/spi/spi.c"),
            bld.path.find_node("test_spi_spi_notification.c"),
        ],
        target="test-app-spi_spi_notification",
        includes=[
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/dma"),
            bld.srcnode.find_node("src/app/driver/io"),
            bld.srcnode.find_node("src/app/driver/spi"),
        ],
        mocks=[
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_sys_dma.h"),
            bld.srcnode.find_node("src/app/driver/config/dma_cfg.h"),
            bld.srcnode.find_node("src/app/driver/io/io.h"),
            bld.srcnode.find_node("src/app/driver/mcu/mcu.h"),
            bld.srcnode.find_node("src/app/task/os/os.h"),
            bld.srcnode.find_node("src/app/driver/config/spi_cfg.h"),
            bld.srcnode.find_node("src/app/driver/config/spi_cfg_initialization.h"),
        ],
        defines=["COMPILE_FOR_UNIT_TEST=1"],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/driver/spi/spi.c"),
            bld.path.find_node("test_spi_st.c"),
        ],
        target="test-app-spi_st",
        includes=[
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/dma"),
            bld.srcnode.find_node("src/app/driver/io"),
            bld.srcnode.find_node("src/app/driver/spi"),
        ],
        mocks=[
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_spi.h"),
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_sys_dma.h"),
            bld.srcnode.find_node("src/app/driver/config/dma_cfg.h"),
            bld.srcnode.find_node("src/app/driver/io/io.h"),
            bld.srcnode.find_node("src/app/driver/mcu/mcu.h"),
            bld.srcnode.find_node("src/app/task/os/os.h"),
            bld.srcnode.find_node("src/app/driver/config/spi_cfg.h"),
            bld.srcnode.find_node("src/app/driver/config/spi_cfg_initialization.h"),
        ],
        defines=[
            "FOXBMS_AFE_DRIVER_ST=1u",
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/driver/spi/spi.c"),
            bld.path.find_node("test_spi_ti.c"),
        ],
        target="test-app-spi_ti",
        includes=[
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/dma"),
            bld.srcnode.find_node("src/app/driver/io"),
            bld.srcnode.find_node("src/app/driver/spi"),
        ],
        mocks=[
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_spi.h"),
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_sys_dma.h"),
            bld.srcnode.find_node("src/app/driver/config/dma_cfg.h"),
            bld.srcnode.find_node("src/app/driver/io/io.h"),
            bld.srcnode.find_node("src/app/driver/mcu/mcu.h"),
            bld.srcnode.find_node("src/app/task/os/os.h"),
            bld.srcnode.find_node("src/app/driver/config/spi_cfg.h"),
            bld.srcnode.find_node("src/app/driver/config/spi_cfg_initialization.h"),
        ],
        defines=[
            "FOXBMS_AFE_DRIVER_TI=1u",
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/driver/spi/spi.c"),
            bld.path.find_node("test_spi.c"),
        ],
        target="test-app-spi",
        includes=[
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/dma"),
            bld.srcnode.find_node("src/app/driver/io"),
            bld.srcnode.find_node("src/app/driver/spi"),
        ],
        mocks=[
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_spi.h"),
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_sys_dma.h"),
            bld.srcnode.find_node("src/app/driver/config/dma_cfg.h"),
            bld.srcnode.find_node("src/app/driver/io/io.h"),
            bld.srcnode.find_node("src/app/driver/mcu/mcu.h"),
            bld.srcnode.find_node("src/app/task/os/os.h"),
            bld.srcnode.find_node("src/app/driver/config/spi_cfg.h"),
            bld.srcnode.find_node("src/app/driver/config/spi_cfg_initialization.h"),
        ],
    )
