#!/usr/bin/env python3
#
# Copyright (c) 2010 - 2026, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"


from waflib.Build import BuildContext


def build(bld: BuildContext) -> None:
    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node(
                "src/app/driver/can/cbs/rx/can_cbs_rx_afe_cell-temperatures.c"
            ),
            bld.path.find_node("test_can_cbs_rx_afe_cell-temperatures.c"),
        ],
        target="test-app-can_cbs_rx_afe_cell-temperatures",
        includes=[
            bld.srcnode.find_node("src/app/driver/can"),
            bld.srcnode.find_node("src/app/driver/can/cbs"),
            bld.srcnode.find_node("src/app/driver/can/cbs/rx"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/rtc"),
            bld.srcnode.find_node("src/app/engine/diag"),
            bld.srcnode.find_node("src/app/task/config"),
            bld.srcnode.find_node("src/app/task/ftask"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/driver/can/can.h"),
            bld.srcnode.find_node("src/app/driver/can/cbs/can_helper.h"),
            bld.srcnode.find_node("src/app/engine/diag/diag.h"),
            bld.srcnode.find_node("src/app/task/ftask/ftask.h"),
            bld.srcnode.find_node("src/app/task/os/os.h"),
        ],
        defines=[
            "FOXBMS_AFE_DRIVER_DEBUG_CAN=1u",
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node(
                "src/app/driver/can/cbs/rx/can_cbs_rx_afe_cell-voltages.c"
            ),
            bld.path.find_node("test_can_cbs_rx_afe_cell-voltages.c"),
        ],
        target="test-app-can_cbs_rx_afe_cell-voltages",
        includes=[
            bld.srcnode.find_node("src/app/driver/can"),
            bld.srcnode.find_node("src/app/driver/can/cbs"),
            bld.srcnode.find_node("src/app/driver/can/cbs/rx"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/rtc"),
            bld.srcnode.find_node("src/app/engine/diag"),
            bld.srcnode.find_node("src/app/task/config"),
            bld.srcnode.find_node("src/app/task/ftask"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/driver/can/can.h"),
            bld.srcnode.find_node("src/app/driver/can/cbs/can_helper.h"),
            bld.srcnode.find_node("src/app/engine/diag/diag.h"),
            bld.srcnode.find_node("src/app/task/ftask/ftask.h"),
            bld.srcnode.find_node("src/app/task/os/os.h"),
        ],
        defines=[
            "FOXBMS_AFE_DRIVER_DEBUG_CAN=1u",
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node(
                "src/app/driver/can/cbs/rx/can_cbs_rx_as_honeywell-bas6c-x00.c"
            ),
            bld.srcnode.find_node("src/app/engine/config/database_cfg.c"),
            bld.srcnode.find_node("src/app/driver/can/cbs/can_helper.c"),
            bld.path.find_node("test_can_cbs_rx_as_honeywell-bas6c-x00.c"),
        ],
        target="test-app-can_cbs_rx_as_honeywell-bas6c-x00",
        includes=[
            bld.srcnode.find_node("src/app/driver/can"),
            bld.srcnode.find_node("src/app/driver/can/cbs"),
            bld.srcnode.find_node("src/app/driver/can/cbs/rx"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/foxmath"),
            bld.srcnode.find_node("src/app/driver/imd"),
            bld.srcnode.find_node("src/app/engine/diag"),
            bld.srcnode.find_node("src/app/task/config"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/driver/can/can.h"),
            bld.srcnode.find_node("src/app/engine/database/database.h"),
            bld.srcnode.find_node("src/app/engine/diag/diag.h"),
            bld.srcnode.find_node("src/app/driver/foxmath/foxmath.h"),
            bld.srcnode.find_node("src/app/driver/imd/imd.h"),
            bld.srcnode.find_node("src/app/task/os/os.h"),
        ],
        defines=[
            "FOXBMS_AS_HONEYWELL_BAS6C_X00=1",
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node(
                "src/app/driver/can/cbs/rx/can_cbs_rx_cs_isabellenhuette-ivt-s.c"
            ),
            bld.srcnode.find_node("src/app/engine/config/database_cfg.c"),
            bld.path.find_node("test_can_cbs_rx_cs_isabellenhuette-ivt-s.c"),
        ],
        target="test-app-can_cbs_rx_cs_isabellenhuette-ivt-s",
        includes=[
            bld.srcnode.find_node("src/app/driver/can"),
            bld.srcnode.find_node("src/app/driver/can/cbs"),
            bld.srcnode.find_node("src/app/driver/can/cbs/rx"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/foxmath"),
            bld.srcnode.find_node("src/app/driver/imd"),
            bld.srcnode.find_node("src/app/engine/diag"),
            bld.srcnode.find_node("src/app/task/config"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/driver/can/can.h"),
            bld.srcnode.find_node("src/app/driver/can/cbs/can_helper.h"),
            bld.srcnode.find_node("src/app/engine/database/database.h"),
            bld.srcnode.find_node("src/app/engine/diag/diag.h"),
            bld.srcnode.find_node("src/app/driver/foxmath/foxmath.h"),
            bld.srcnode.find_node("src/app/driver/imd/imd.h"),
            bld.srcnode.find_node("src/app/task/os/os.h"),
        ],
        defines=[
            "FOXBMS_CS_ISABELLENHUETTE_IVT_S=1",
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node(
                "src/app/driver/can/cbs/rx/can_cbs_rx_cs_lem-cab500.c"
            ),
            bld.srcnode.find_node("src/app/engine/config/database_cfg.c"),
            bld.path.find_node("test_can_cbs_rx_cs_lem-cab500.c"),
        ],
        target="test-app-can_cbs_rx_cs_lem-cab500",
        includes=[
            bld.srcnode.find_node("src/app/driver/can"),
            bld.srcnode.find_node("src/app/driver/can/cbs"),
            bld.srcnode.find_node("src/app/driver/can/cbs/rx"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/foxmath"),
            bld.srcnode.find_node("src/app/driver/imd"),
            bld.srcnode.find_node("src/app/engine/diag"),
            bld.srcnode.find_node("src/app/task/config"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/driver/can/can.h"),
            bld.srcnode.find_node("src/app/driver/can/cbs/can_helper.h"),
            bld.srcnode.find_node("src/app/engine/database/database.h"),
            bld.srcnode.find_node("src/app/engine/diag/diag.h"),
            bld.srcnode.find_node("src/app/driver/foxmath/foxmath.h"),
            bld.srcnode.find_node("src/app/driver/imd/imd.h"),
            bld.srcnode.find_node("src/app/task/os/os.h"),
        ],
        defines=[
            "FOXBMS_CS_LEM_CAB500=1",
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node(
                "src/app/driver/can/cbs/rx/can_cbs_rx_f_bms-state-request.c"
            ),
            bld.srcnode.find_node("src/app/engine/config/database_cfg.c"),
            bld.path.find_node("test_can_cbs_rx_f_bms-state-request.c"),
        ],
        target="test-app-can_cbs_rx_f_bms-state-request",
        includes=[
            bld.srcnode.find_node("src/app/application/bal"),
            bld.srcnode.find_node("src/app/driver/can"),
            bld.srcnode.find_node("src/app/driver/can/cbs"),
            bld.srcnode.find_node("src/app/driver/can/cbs/rx"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/foxmath"),
            bld.srcnode.find_node("src/app/driver/fram"),
            bld.srcnode.find_node("src/app/driver/imd"),
            bld.srcnode.find_node("src/app/engine/diag"),
            bld.srcnode.find_node("src/app/engine/sys_mon"),
            bld.srcnode.find_node("src/app/task/config"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/application/bal/bal.h"),
            bld.srcnode.find_node("src/app/application/config/bal_cfg.h"),
            bld.srcnode.find_node("src/app/application/config/bms_cfg.h"),
            bld.srcnode.find_node("src/app/driver/can/can.h"),
            bld.srcnode.find_node("src/app/driver/can/cbs/can_helper.h"),
            bld.srcnode.find_node("src/app/engine/database/database.h"),
            bld.srcnode.find_node("src/app/engine/diag/diag.h"),
            bld.srcnode.find_node("src/app/driver/foxmath/foxmath.h"),
            bld.srcnode.find_node("src/app/driver/imd/imd.h"),
            bld.srcnode.find_node("src/app/task/os/os.h"),
            bld.srcnode.find_node("src/app/engine/sys_mon/sys_mon.h"),
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/driver/can/cbs/rx/can_cbs_rx_f_debug.c"),
            bld.srcnode.find_node("src/app/engine/config/database_cfg.c"),
            bld.srcnode.find_node("src/app/driver/config/fram_cfg.c"),
            bld.srcnode.find_node("src/app/driver/can/cbs/can_helper.c"),
            bld.srcnode.find_node("src/app/engine/sys/sys.c"),
            bld.path.find_node("test_can_cbs_rx_f_debug.c"),
        ],
        target="test-app-can_cbs_rx_f_debug",
        includes=[
            bld.srcnode.find_node("src/app/application/algorithm"),
            bld.srcnode.find_node("src/app/application/algorithm/config"),
            bld.srcnode.find_node("src/app/application/algorithm/state_estimation"),
            bld.srcnode.find_node(
                "src/app/application/algorithm/state_estimation/sof/trapezoid"
            ),
            bld.srcnode.find_node("src/app/application/bal"),
            bld.srcnode.find_node("src/app/application/bms"),
            bld.srcnode.find_node("src/app/driver/afe/api"),
            bld.srcnode.find_node("src/app/driver/can"),
            bld.srcnode.find_node("src/app/driver/can/cbs"),
            bld.srcnode.find_node("src/app/driver/can/cbs/rx"),
            bld.srcnode.find_node("src/app/driver/can/cbs/tx-async"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/contactor"),
            bld.srcnode.find_node("src/app/driver/dma"),
            bld.srcnode.find_node("src/app/driver/foxmath"),
            bld.srcnode.find_node("src/app/driver/fram"),
            bld.srcnode.find_node("src/app/driver/i2c"),
            bld.srcnode.find_node("src/app/driver/imd"),
            bld.srcnode.find_node("src/app/driver/interlock"),
            bld.srcnode.find_node("src/app/driver/mcu"),
            bld.srcnode.find_node("src/app/driver/meas"),
            bld.srcnode.find_node("src/app/driver/rtc"),
            bld.srcnode.find_node("src/app/driver/sbc"),
            bld.srcnode.find_node("src/app/driver/sbc/fs8x_driver"),
            bld.srcnode.find_node("src/app/driver/spi"),
            bld.srcnode.find_node("src/app/driver/sps"),
            bld.srcnode.find_node("src/app/engine/diag"),
            bld.srcnode.find_node("src/app/engine/sys"),
            bld.srcnode.find_node("src/app/task/config"),
            bld.srcnode.find_node("src/app/task/ftask"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/driver/afe/api/afe.h"),
            bld.srcnode.find_node("src/app/application/algorithm/algorithm.h"),
            bld.srcnode.find_node("src/app/application/bal/bal.h"),
            bld.srcnode.find_node("src/app/application/bms/bms.h"),
            bld.srcnode.find_node("src/app/driver/can/can.h"),
            bld.srcnode.find_node(
                "src/app/driver/can/cbs/tx-async/can_cbs_tx_f_debug-build-configuration.h"
            ),
            bld.srcnode.find_node(
                "src/app/driver/can/cbs/tx-async/can_cbs_tx_f_debug-identify-hardware.h"
            ),
            bld.srcnode.find_node(
                "src/app/driver/can/cbs/tx-async/can_cbs_tx_f_debug-response.h"
            ),
            bld.srcnode.find_node(
                "src/app/driver/can/cbs/tx-async/"
                "can_cbs_tx_f_debug-unsupported-multiplexer-values.h"
            ),
            bld.srcnode.find_node("src/app/driver/contactor/contactor.h"),
            bld.srcnode.find_node("src/app/engine/database/database.h"),
            bld.srcnode.find_node("src/app/engine/diag/diag.h"),
            bld.srcnode.find_node("src/app/driver/foxmath/foxmath.h"),
            bld.srcnode.find_node("src/app/driver/fram/fram.h"),
            bld.srcnode.find_node("src/app/driver/imd/imd.h"),
            bld.srcnode.find_node("src/app/driver/interlock/interlock.h"),
            bld.srcnode.find_node("src/app/driver/mcu/mcu.h"),
            bld.srcnode.find_node("src/app/driver/meas/meas.h"),
            bld.srcnode.find_node("src/app/task/os/os.h"),
            bld.srcnode.find_node("src/app/engine/sys/reset.h"),
            bld.srcnode.find_node("src/app/driver/rtc/rtc.h"),
            bld.srcnode.find_node("src/app/driver/sbc/sbc.h"),
            bld.srcnode.find_node(
                "src/app/application/algorithm/state_estimation/sof/trapezoid/sof_trapezoid.h"
            ),
            bld.srcnode.find_node(
                "src/app/application/algorithm/state_estimation/state_estimation.h"
            ),
            bld.srcnode.find_node("src/app/engine/config/sys_cfg.h"),
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node(
                "src/app/driver/can/cbs/rx/can_cbs_rx_imd_bender-iso165c-info.c"
            ),
            bld.srcnode.find_node("src/app/engine/config/database_cfg.c"),
            bld.srcnode.find_node("src/app/driver/can/cbs/can_helper.c"),
            bld.path.find_node("test_can_cbs_rx_imd_bender-iso165c-info.c"),
        ],
        target="test-app-can_cbs_rx_imd_bender-iso165c-info",
        includes=[
            bld.srcnode.find_node("src/app/driver/can"),
            bld.srcnode.find_node("src/app/driver/can/cbs"),
            bld.srcnode.find_node("src/app/driver/can/cbs/rx"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/foxmath"),
            bld.srcnode.find_node("src/app/driver/imd"),
            bld.srcnode.find_node("src/app/driver/imd/bender/iso165c/config"),
            bld.srcnode.find_node("src/app/engine/diag"),
            bld.srcnode.find_node("src/app/task/config"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/driver/can/can.h"),
            bld.srcnode.find_node("src/app/engine/database/database.h"),
            bld.srcnode.find_node("src/app/engine/diag/diag.h"),
            bld.srcnode.find_node("src/app/driver/foxmath/foxmath.h"),
            bld.srcnode.find_node("src/app/driver/imd/imd.h"),
            bld.srcnode.find_node("src/app/task/os/os.h"),
        ],
        defines=[
            "FOXBMS_IMD_BENDER_ISO165C=1",
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node(
                "src/app/driver/can/cbs/rx/can_cbs_rx_imd_bender-iso165c-response.c"
            ),
            bld.srcnode.find_node("src/app/engine/config/database_cfg.c"),
            bld.path.find_node("test_can_cbs_rx_imd_bender-iso165c-response.c"),
        ],
        target="test-app-can_cbs_rx_imd_bender-iso165c-response",
        includes=[
            bld.srcnode.find_node("src/app/driver/can"),
            bld.srcnode.find_node("src/app/driver/can/cbs"),
            bld.srcnode.find_node("src/app/driver/can/cbs/rx"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/foxmath"),
            bld.srcnode.find_node("src/app/driver/imd"),
            bld.srcnode.find_node("src/app/driver/imd/bender/iso165c/config"),
            bld.srcnode.find_node("src/app/engine/diag"),
            bld.srcnode.find_node("src/app/engine/sys_mon"),
            bld.srcnode.find_node("src/app/task/config"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/driver/can/can.h"),
            bld.srcnode.find_node("src/app/driver/can/cbs/can_helper.h"),
            bld.srcnode.find_node("src/app/engine/database/database.h"),
            bld.srcnode.find_node("src/app/engine/diag/diag.h"),
            bld.srcnode.find_node("src/app/driver/foxmath/foxmath.h"),
            bld.srcnode.find_node("src/app/driver/imd/imd.h"),
            bld.srcnode.find_node("src/app/task/os/os.h"),
        ],
        defines=[
            "FOXBMS_IMD_BENDER_ISO165C=1",
        ],
    )
