#!/usr/bin/env python3
#
# Copyright (c) 2010 - 2026, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"


from waflib.Build import BuildContext


def build(bld: BuildContext) -> None:
    bld.recurse("freertos")

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/task/ftask/ftask.c"),
            bld.path.find_node("test_ftask.c"),
        ],
        target="test-app-ftask",
        includes=[
            bld.srcnode.find_node("src/app/application/algorithm"),
            bld.srcnode.find_node("src/app/application/algorithm/config"),
            bld.srcnode.find_node("src/app/application/algorithm/state_estimation"),
            bld.srcnode.find_node(
                "src/app/application/algorithm/state_estimation/sof/trapezoid"
            ),
            bld.srcnode.find_node("src/app/application/bal"),
            bld.srcnode.find_node("src/app/application/bms"),
            bld.srcnode.find_node("src/app/application/redundancy"),
            bld.srcnode.find_node("src/app/driver/adc"),
            bld.srcnode.find_node("src/app/driver/afe/api"),
            bld.srcnode.find_node("src/app/driver/can"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/contactor"),
            bld.srcnode.find_node("src/app/driver/dma"),
            bld.srcnode.find_node("src/app/driver/emac"),
            bld.srcnode.find_node("src/app/driver/fram"),
            bld.srcnode.find_node("src/app/driver/htsensor"),
            bld.srcnode.find_node("src/app/driver/i2c"),
            bld.srcnode.find_node("src/app/driver/imd"),
            bld.srcnode.find_node("src/app/driver/interlock"),
            bld.srcnode.find_node("src/app/driver/led"),
            bld.srcnode.find_node("src/app/driver/meas"),
            bld.srcnode.find_node("src/app/driver/pex"),
            bld.srcnode.find_node("src/app/driver/phy"),
            bld.srcnode.find_node("src/app/driver/rtc"),
            bld.srcnode.find_node("src/app/driver/sbc"),
            bld.srcnode.find_node("src/app/driver/sbc/fs8x_driver"),
            bld.srcnode.find_node("src/app/driver/spi"),
            bld.srcnode.find_node("src/app/driver/sps"),
            bld.srcnode.find_node("src/app/engine/diag"),
            bld.srcnode.find_node("src/app/engine/hw_info"),
            bld.srcnode.find_node("src/app/engine/sys"),
            bld.srcnode.find_node("src/app/engine/sys_mon"),
            bld.srcnode.find_node("src/app/task/config"),
            bld.srcnode.find_node("src/app/task/ftask"),
        ],
        mocks=[
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_gio.h"),
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_mdio.h"),
            bld.srcnode.find_node("src/app/driver/adc/adc.h"),
            bld.srcnode.find_node("src/app/driver/afe/api/afe.h"),
            bld.srcnode.find_node("src/app/application/algorithm/algorithm.h"),
            bld.srcnode.find_node("src/app/application/bal/bal.h"),
            bld.srcnode.find_node("src/app/application/bms/bms.h"),
            bld.srcnode.find_node("src/app/driver/can/can.h"),
            bld.srcnode.find_node("src/app/driver/contactor/contactor.h"),
            bld.srcnode.find_node("src/app/engine/database/database.h"),
            bld.srcnode.find_node("src/app/engine/diag/diag.h"),
            bld.srcnode.find_node("src/app/engine/config/diag_cfg.h"),
            bld.srcnode.find_node("src/app/driver/fram/fram.h"),
            bld.srcnode.find_node("src/app/task/config/ftask_cfg.h"),
            bld.srcnode.find_node("src/app/driver/htsensor/htsensor.h"),
            bld.srcnode.find_node("src/app/driver/i2c/i2c.h"),
            bld.srcnode.find_node("src/app/driver/imd/imd.h"),
            bld.srcnode.find_node("src/app/main/include/infinite-loop-helper.h"),
            bld.srcnode.find_node("src/app/driver/interlock/interlock.h"),
            bld.srcnode.find_node("src/app/driver/led/led.h"),
            bld.srcnode.find_node("src/app/engine/hw_info/master_info.h"),
            bld.srcnode.find_node("src/app/driver/meas/meas.h"),
            bld.srcnode.find_node("src/os/freertos/freertos/include/mpu_prototypes.h"),
            bld.srcnode.find_node("src/app/task/os/os.h"),
            bld.srcnode.find_node("src/app/driver/pex/pex.h"),
            bld.srcnode.find_node("src/app/application/redundancy/redundancy.h"),
            bld.srcnode.find_node("src/app/driver/rtc/rtc.h"),
            bld.srcnode.find_node("src/app/driver/sbc/sbc.h"),
            bld.srcnode.find_node(
                "src/app/application/algorithm/state_estimation/sof/trapezoid/sof_trapezoid.h"
            ),
            bld.srcnode.find_node("src/app/driver/sps/sps.h"),
            bld.srcnode.find_node(
                "src/app/application/algorithm/state_estimation/state_estimation.h"
            ),
            bld.srcnode.find_node("src/app/engine/sys/sys.h"),
            bld.srcnode.find_node("src/app/engine/sys_mon/sys_mon.h"),
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/task/ftask/ftask.c"),
            bld.path.find_node("test_ftask_emac.c"),
        ],
        target="test-app-ftask_emac",
        includes=[
            bld.srcnode.find_node("src/app/application/algorithm"),
            bld.srcnode.find_node("src/app/application/algorithm/config"),
            bld.srcnode.find_node("src/app/application/algorithm/state_estimation"),
            bld.srcnode.find_node(
                "src/app/application/algorithm/state_estimation/sof/trapezoid"
            ),
            bld.srcnode.find_node("src/app/application/bal"),
            bld.srcnode.find_node("src/app/application/bms"),
            bld.srcnode.find_node("src/app/application/redundancy"),
            bld.srcnode.find_node("src/app/driver/adc"),
            bld.srcnode.find_node("src/app/driver/afe/api"),
            bld.srcnode.find_node("src/app/driver/can"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/contactor"),
            bld.srcnode.find_node("src/app/driver/dma"),
            bld.srcnode.find_node("src/app/driver/emac"),
            bld.srcnode.find_node("src/app/driver/fram"),
            bld.srcnode.find_node("src/app/driver/htsensor"),
            bld.srcnode.find_node("src/app/driver/i2c"),
            bld.srcnode.find_node("src/app/driver/imd"),
            bld.srcnode.find_node("src/app/driver/interlock"),
            bld.srcnode.find_node("src/app/driver/led"),
            bld.srcnode.find_node("src/app/driver/meas"),
            bld.srcnode.find_node("src/app/driver/pex"),
            bld.srcnode.find_node("src/app/driver/phy"),
            bld.srcnode.find_node("src/app/driver/rtc"),
            bld.srcnode.find_node("src/app/driver/sbc"),
            bld.srcnode.find_node("src/app/driver/sbc/fs8x_driver"),
            bld.srcnode.find_node("src/app/driver/spi"),
            bld.srcnode.find_node("src/app/driver/sps"),
            bld.srcnode.find_node("src/app/driver/uart"),
            bld.srcnode.find_node("src/app/engine/diag"),
            bld.srcnode.find_node("src/app/engine/hw_info"),
            bld.srcnode.find_node("src/app/engine/sys"),
            bld.srcnode.find_node("src/app/engine/sys_mon"),
            bld.srcnode.find_node("src/app/task/config"),
            bld.srcnode.find_node("src/app/task/ftask"),
            bld.srcnode.find_node(
                "src/os/freertos/freertos-plus/freertos-plus-tcp/source/include"
            ),
            bld.srcnode.find_node(
                "src/os/freertos/freertos-plus/freertos-plus-tcp/source/portable/Compiler/CCS"
            ),
        ],
        mocks=[
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_gio.h"),
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_mdio.h"),
            bld.srcnode.find_node("src/app/driver/adc/adc.h"),
            bld.srcnode.find_node("src/app/driver/afe/api/afe.h"),
            bld.srcnode.find_node("src/app/application/algorithm/algorithm.h"),
            bld.srcnode.find_node("src/app/application/bal/bal.h"),
            bld.srcnode.find_node("src/app/application/bms/bms.h"),
            bld.srcnode.find_node("src/app/driver/can/can.h"),
            bld.srcnode.find_node("src/app/driver/contactor/contactor.h"),
            bld.srcnode.find_node("src/app/engine/database/database.h"),
            bld.srcnode.find_node("src/app/engine/diag/diag.h"),
            bld.srcnode.find_node("src/app/engine/config/diag_cfg.h"),
            bld.srcnode.find_node("src/app/driver/emac/emac.h"),
            bld.srcnode.find_node("src/app/driver/fram/fram.h"),
            bld.srcnode.find_node("src/app/task/config/ftask_cfg.h"),
            bld.srcnode.find_node("src/app/driver/htsensor/htsensor.h"),
            bld.srcnode.find_node("src/app/driver/i2c/i2c.h"),
            bld.srcnode.find_node("src/app/driver/imd/imd.h"),
            bld.srcnode.find_node("src/app/main/include/infinite-loop-helper.h"),
            bld.srcnode.find_node("src/app/driver/interlock/interlock.h"),
            bld.srcnode.find_node("src/app/driver/led/led.h"),
            bld.srcnode.find_node("src/app/engine/hw_info/master_info.h"),
            bld.srcnode.find_node("src/app/driver/meas/meas.h"),
            bld.srcnode.find_node("src/os/freertos/freertos/include/mpu_prototypes.h"),
            bld.srcnode.find_node("src/app/task/os/os.h"),
            bld.srcnode.find_node("src/app/driver/pex/pex.h"),
            bld.srcnode.find_node("src/app/application/redundancy/redundancy.h"),
            bld.srcnode.find_node("src/app/driver/rtc/rtc.h"),
            bld.srcnode.find_node("src/app/driver/sbc/sbc.h"),
            bld.srcnode.find_node(
                "src/app/application/algorithm/state_estimation/sof/trapezoid/sof_trapezoid.h"
            ),
            bld.srcnode.find_node("src/app/driver/sps/sps.h"),
            bld.srcnode.find_node(
                "src/app/application/algorithm/state_estimation/state_estimation.h"
            ),
            bld.srcnode.find_node("src/app/engine/sys/sys.h"),
            bld.srcnode.find_node("src/app/engine/sys_mon/sys_mon.h"),
        ],
        defines=[
            "FOXBMS_TCP_SUPPORT=1",
            "FOXBMS_UART_SUPPORT=1",
        ],
        cflags=[
            "-I",
            "../../src/os/freertos/freertos/include",
            "-include",
            "FreeRTOSConfig.h",
        ],
    )
