#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (c) 2010 - 2021, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"

"""builds the AFE driver for MAX17852"""

import os


def build(bld):
    """builds the AFE driver library for Maxim"""
    source = [
        os.path.join(".", "mxm_17852.c"),
        os.path.join("..", "api", "mxm_afe.c"),
        os.path.join("..", "common", "config", "mxm_cfg.c"),
        os.path.join("..", "common", "mxm_17841b.c"),
        os.path.join("..", "common", "mxm_1785x.c"),
        os.path.join("..", "common", "mxm_1785x_tools.c"),
        os.path.join("..", "common", "mxm_battery_management.c"),
        os.path.join("..", "common", "mxm_bitextract.c"),
        os.path.join("..", "common", "mxm_crc8.c"),
        os.path.join("..", "common", "mxm_afe_dma.c"),
        os.path.join("..", "common", "mxm_registry.c"),
        os.path.join("..", "..", "api", "afe_plausibility.c"),
    ]
    includes = [
        ".",
        os.path.join("..", "api"),
        os.path.join("..", "common"),
        os.path.join("..", "common", "config"),
        os.path.join("..", "..", "api"),
        os.path.join("..", "..", "..", "config"),
        os.path.join("..", "..", "..", "foxmath"),
        os.path.join("..", "..", "..", "io"),
        os.path.join("..", "..", "..", "spi"),
        os.path.join("..", "..", "..", "ts"),
        os.path.join("..", "..", "..", "ts", "api"),
        os.path.join("..", "..", "..", "..", "application", "config"),
        os.path.join("..", "..", "..", "..", "main", "include"),
        os.path.join("..", "..", "..", "..", "engine", "config"),
        os.path.join("..", "..", "..", "..", "engine", "database"),
        os.path.join("..", "..", "..", "..", "engine", "diag"),
        os.path.join("..", "..", "..", "..", "task", "os"),
    ]
    includes.extend(bld.env.INCLUDES_OPERATING_SYSTEM)
    cflags = bld.env.CFLAGS_FOXBMS
    target = f"{bld.env.APPNAME.lower()}-afe-driver"
    bld.objects(
        source=source,
        includes=includes,
        cflags=cflags,
        target=target,
    )
