#!/usr/bin/env python3
#
# Copyright (c) 2010 - 2026, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"


from waflib.Build import BuildContext


def build(bld: BuildContext) -> None:
    bld.recurse(["api", "config"])

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node(
                "src/app/driver/afe/nxp/mc33775a/nxp_mc33775a_alarm.c"
            ),
            bld.path.find_node("test_nxp_mc33775a_alarm.c"),
        ],
        target="test-app-nxp_mc33775a_alarm",
        includes=[
            bld.srcnode.find_node("src/app/driver/afe/nxp/common/mc3377x"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/common/mc3377x/vendor"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/mc33775a"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/mc33775a/config"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/mc33775a/vendor"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/spi"),
            bld.srcnode.find_node("src/app/engine/diag"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/engine/database/database.h"),
            bld.srcnode.find_node("src/app/engine/diag/diag.h"),
            bld.srcnode.find_node(
                "src/app/driver/afe/nxp/common/mc3377x/nxp_mc3377x-ll.h"
            ),
        ],
        defines=[
            "FOXBMS_AFE_DRIVER_TYPE_NO_FSM=1",
            "FOXBMS_AFE_DRIVER_NXP=1u",
            "FOXBMS_AFE_DRIVER_NXP_MC33775A",
            "TEST_BS_NR_OF_CELL_BLOCKS_PER_MODULE=14u",
            "TEST_BS_NR_OF_TEMP_SENSORS_PER_MODULE=16u",
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node(
                "src/app/driver/afe/nxp/mc33775a/nxp_mc33775a_balancing.c"
            ),
            bld.path.find_node("test_nxp_mc33775a_balancing.c"),
        ],
        target="test-app-nxp_mc33775a_balancing",
        includes=[
            bld.srcnode.find_node("src/app/driver/afe/nxp/common/mc3377x"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/common/mc3377x/vendor"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/mc33775a"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/mc33775a/config"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/mc33775a/vendor"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/spi"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/engine/database/database.h"),
            bld.srcnode.find_node(
                "src/app/driver/afe/nxp/common/mc3377x/nxp_mc3377x-ll.h"
            ),
        ],
        defines=[
            "FOXBMS_AFE_DRIVER_TYPE_NO_FSM=1",
            "FOXBMS_AFE_DRIVER_NXP=1u",
            "FOXBMS_AFE_DRIVER_NXP_MC33775A",
            "TEST_BS_NR_OF_CELL_BLOCKS_PER_MODULE=14u",
            "TEST_BS_NR_OF_TEMP_SENSORS_PER_MODULE=16u",
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node(
                "src/app/driver/afe/nxp/common/mc3377x/nxp_mc3377x_database.c"
            ),
            bld.path.find_node("test_nxp_mc33775a_database.c"),
        ],
        target="test-app-nxp_mc33775a_database",
        includes=[
            bld.srcnode.find_node("src/app/driver/afe/nxp/common/mc3377x"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/mc33775a"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/mc33775a/config"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/mc33775a/vendor"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/spi"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/engine/database/database.h"),
        ],
        defines=[
            "FOXBMS_AFE_DRIVER_TYPE_NO_FSM=1",
            "FOXBMS_AFE_DRIVER_NXP=1u",
            "FOXBMS_AFE_DRIVER_NXP_MC33775A",
            "TEST_BS_NR_OF_CELL_BLOCKS_PER_MODULE=14u",
            "TEST_BS_NR_OF_TEMP_SENSORS_PER_MODULE=16u",
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node(
                "src/app/driver/afe/nxp/common/mc3377x/nxp_mc3377x_helpers.c"
            ),
            bld.path.find_node("test_nxp_mc33775a_helpers.c"),
        ],
        target="test-app-nxp_mc33775a_helpers",
        includes=[
            bld.srcnode.find_node("src/app/driver/afe/nxp/common/mc3377x"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/common/mc3377x/vendor"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/mc33775a"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/mc33775a/config"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/mc33775a/vendor"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/spi"),
            bld.srcnode.find_node("src/app/driver/ts/api"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/task/os/os.h"),
            bld.srcnode.find_node("src/app/driver/ts/api/tsi.h"),
        ],
        defines=[
            "FOXBMS_AFE_DRIVER_TYPE_NO_FSM=1",
            "FOXBMS_AFE_DRIVER_NXP=1u",
            "FOXBMS_AFE_DRIVER_NXP_MC33775A",
            "TEST_BS_NR_OF_CELL_BLOCKS_PER_MODULE=14u",
            "TEST_BS_NR_OF_TEMP_SENSORS_PER_MODULE=16u",
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/driver/afe/nxp/mc33775a/nxp_mc33775a_i2c.c"),
            bld.path.find_node("test_nxp_mc33775a_i2c.c"),
        ],
        target="test-app-nxp_mc33775a_i2c",
        includes=[
            bld.srcnode.find_node("src/app/driver/afe/api"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/common/mc3377x"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/common/mc3377x/vendor"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/mc33775a"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/mc33775a/config"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/mc33775a/vendor"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/rtc"),
            bld.srcnode.find_node("src/app/driver/spi"),
            bld.srcnode.find_node("src/app/task/config"),
            bld.srcnode.find_node("src/app/task/ftask"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/engine/database/database.h"),
            bld.srcnode.find_node("src/app/task/ftask/ftask.h"),
            bld.srcnode.find_node(
                "src/app/driver/afe/nxp/common/mc3377x/nxp_mc3377x-ll.h"
            ),
            bld.srcnode.find_node(
                "src/app/driver/afe/nxp/common/mc3377x/nxp_mc3377x_cfg.h"
            ),
            bld.srcnode.find_node(
                "src/app/driver/afe/nxp/common/mc3377x/nxp_mc3377x_helpers.h"
            ),
            bld.srcnode.find_node("src/app/task/os/os.h"),
        ],
        defines=[
            "FOXBMS_AFE_DRIVER_TYPE_NO_FSM=1",
            "FOXBMS_AFE_DRIVER_NXP=1u",
            "FOXBMS_AFE_DRIVER_NXP_MC33775A",
            "TEST_BS_NR_OF_CELL_BLOCKS_PER_MODULE=14u",
            "TEST_BS_NR_OF_TEMP_SENSORS_PER_MODULE=16u",
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node(
                "src/app/driver/afe/nxp/mc33775a/nxp_mc33775a_measurement.c"
            ),
            bld.path.find_node("test_nxp_mc33775a_measurement.c"),
        ],
        target="test-app-nxp_mc33775a_measurement",
        includes=[
            bld.srcnode.find_node("src/app/driver/afe/api"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/common/mc3377x"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/common/mc3377x/vendor"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/mc33775a"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/mc33775a/config"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/mc33775a/vendor"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/foxmath"),
            bld.srcnode.find_node("src/app/driver/spi"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/engine/database/database.h"),
            bld.srcnode.find_node(
                "src/app/driver/afe/nxp/common/mc3377x/nxp_mc3377x-ll.h"
            ),
            bld.srcnode.find_node(
                "src/app/driver/afe/nxp/common/mc3377x/nxp_mc3377x_cfg.h"
            ),
            bld.srcnode.find_node(
                "src/app/driver/afe/nxp/common/mc3377x/nxp_mc3377x_helpers.h"
            ),
        ],
        defines=[
            "FOXBMS_AFE_DRIVER_TYPE_NO_FSM=1",
            "FOXBMS_AFE_DRIVER_NXP=1u",
            "FOXBMS_AFE_DRIVER_NXP_MC33775A",
            "TEST_BS_NR_OF_CELL_BLOCKS_PER_MODULE=14u",
            "TEST_BS_NR_OF_TEMP_SENSORS_PER_MODULE=16u",
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node(
                "src/app/driver/afe/nxp/common/mc3377x/nxp_mc3377x_mux.c"
            ),
            bld.path.find_node("test_nxp_mc33775a_mux.c"),
        ],
        target="test-app-nxp_mc33775a_mux",
        includes=[
            bld.srcnode.find_node("src/app/driver/afe/api"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/common/mc3377x"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/common/mc3377x/vendor"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/mc33775a"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/mc33775a/config"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/mc33775a/vendor"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/spi"),
        ],
        mocks=[
            bld.srcnode.find_node(
                "src/app/driver/afe/nxp/common/mc3377x/nxp_mc3377x-ll.h"
            ),
            bld.srcnode.find_node(
                "src/app/driver/afe/nxp/common/mc3377x/nxp_mc3377x_helpers.h"
            ),
            bld.srcnode.find_node("src/app/task/os/os.h"),
        ],
        defines=[
            "FOXBMS_AFE_DRIVER_TYPE_NO_FSM=1",
            "FOXBMS_AFE_DRIVER_NXP=1u",
            "FOXBMS_AFE_DRIVER_NXP_MC33775A",
            "TEST_BS_NR_OF_CELL_BLOCKS_PER_MODULE=14u",
            "TEST_BS_NR_OF_TEMP_SENSORS_PER_MODULE=16u",
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node(
                "src/app/driver/afe/nxp/common/mc3377x/nxp_mc3377x-ll.c"
            ),
            bld.srcnode.find_node(
                "src/app/driver/afe/nxp/common/mc3377x/vendor/uc_msg_t.c"
            ),
            bld.path.find_node("test_nxp_mc33775a-ll.c"),
        ],
        target="test-app-nxp_mc33775a-ll",
        includes=[
            bld.srcnode.find_node("src/app/driver/afe/api"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/common/mc3377x"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/common/mc3377x/vendor"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/mc33775a"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/mc33775a/config"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/mc33775a/vendor"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/dma"),
            bld.srcnode.find_node("src/app/driver/io"),
            bld.srcnode.find_node("src/app/driver/spi"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/driver/dma/dma.h"),
            bld.srcnode.find_node("src/app/driver/io/io.h"),
            bld.srcnode.find_node("src/app/driver/mcu/mcu.h"),
            bld.srcnode.find_node("src/app/task/os/os.h"),
            bld.srcnode.find_node("src/app/driver/spi/spi.h"),
        ],
        defines=[
            "FOXBMS_AFE_DRIVER_TYPE_NO_FSM=1",
            "FOXBMS_AFE_DRIVER_NXP=1u",
            "FOXBMS_AFE_DRIVER_NXP_MC33775A",
            "TEST_BS_NR_OF_CELL_BLOCKS_PER_MODULE=14u",
            "TEST_BS_NR_OF_TEMP_SENSORS_PER_MODULE=16u",
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node(
                "src/app/driver/afe/nxp/common/mc3377x/nxp_mc3377x.c"
            ),
            bld.path.find_node("test_nxp_mc33775a.c"),
        ],
        target="test-app-nxp_mc33775a",
        includes=[
            bld.srcnode.find_node("src/app/driver/afe/api"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/common/mc3377x"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/common/mc3377x/vendor"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/mc33775a"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/mc33775a/config"),
            bld.srcnode.find_node("src/app/driver/afe/nxp/mc33775a/vendor"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/spi"),
        ],
        mocks=[
            bld.srcnode.find_node(
                "src/app/driver/afe/nxp/common/mc3377x/nxp_mc3377x-ll.h"
            ),
            bld.srcnode.find_node(
                "src/app/driver/afe/nxp/common/mc3377x/nxp_mc3377x_alarm.h"
            ),
            bld.srcnode.find_node(
                "src/app/driver/afe/nxp/common/mc3377x/nxp_mc3377x_balancing.h"
            ),
            bld.srcnode.find_node(
                "src/app/driver/afe/nxp/common/mc3377x/nxp_mc3377x_cfg.h"
            ),
            bld.srcnode.find_node(
                "src/app/driver/afe/nxp/common/mc3377x/nxp_mc3377x_database.h"
            ),
            bld.srcnode.find_node(
                "src/app/driver/afe/nxp/common/mc3377x/nxp_mc3377x_helpers.h"
            ),
            bld.srcnode.find_node(
                "src/app/driver/afe/nxp/common/mc3377x/nxp_mc3377x_i2c.h"
            ),
            bld.srcnode.find_node(
                "src/app/driver/afe/nxp/common/mc3377x/nxp_mc3377x_measurement.h"
            ),
            bld.srcnode.find_node(
                "src/app/driver/afe/nxp/common/mc3377x/nxp_mc3377x_mux.h"
            ),
            bld.srcnode.find_node("src/app/task/os/os.h"),
        ],
        defines=[
            "FOXBMS_AFE_DRIVER_TYPE_NO_FSM=1",
            "FOXBMS_AFE_DRIVER_NXP=1u",
            "FOXBMS_AFE_DRIVER_NXP_MC33775A",
            "TEST_BS_NR_OF_CELL_BLOCKS_PER_MODULE=14u",
            "TEST_BS_NR_OF_TEMP_SENSORS_PER_MODULE=16u",
        ],
    )
