#!/usr/bin/env python3
#
# Copyright (c) 2010 - 2026, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"


def build(bld):
    op = f"{bld.env.APPNAME.lower()}-object-"

    includes = [
        ".",
        "../mcu",
        "../rtc",
        "../can/cbs/rx",
        "../../application/config",
        "../../engine/config",
        "../../engine/database",
        "../../main/include",
        "../../task/config",
        "../../task/ftask",
        "../../task/os",
    ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
    source = "can_cfg_rx"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        cflags=bld.env.CFLAGS_FOXBMS,
        target=f"{op}{source}",
        idx=1,
    )

    includes = [
        ".",
        "../mcu",
        "../rtc",
        "../can/cbs/rx",
        "../can/cbs/tx-cyclic",
        "../../application/config",
        "../../engine/config",
        "../../engine/database",
        "../../main/include",
        "../../task/config",
        "../../task/ftask",
        "../../task/os",
    ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
    source = "can_cfg_tx_cyclic"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        cflags=bld.env.CFLAGS_FOXBMS,
        target=f"{op}{source}",
        idx=1,
    )

    includes = [
        ".",
        "../mcu",
        "../rtc",
        "../../application/config",
        "../../engine/config",
        "../../engine/database",
        "../../main/include",
        "../../task/config",
        "../../task/ftask",
        "../../task/os",
    ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
    source = "can_cfg"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        cflags=bld.env.CFLAGS_FOXBMS,
        target=f"{op}{source}",
        idx=1,
    )

    includes = [
        ".",
        "../sps",
        "../../application/config",
        "../../main/include",
    ]
    source = "contactor_cfg"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        cflags=bld.env.CFLAGS_FOXBMS,
        target=f"{op}{source}",
        idx=1,
    )

    includes = [
        ".",
        "../spi",
        "../../application/config",
        "../../main/include",
    ]
    source = "dma_cfg"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        cflags=bld.env.CFLAGS_FOXBMS,
        target=f"{op}{source}",
        idx=1,
    )

    includes = [
        ".",
        "../spi",
        "../../application/config",
        "../../main/include",
    ]
    source = "fram_cfg"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        cflags=bld.env.CFLAGS_FOXBMS,
        target=f"{op}{source}",
        idx=1,
    )

    includes = [
        ".",
        "../spi",
        "../mcu",
        "../../application/config",
        "../../engine/config",
        "../../engine/database",
        "../../main/include",
        "../../task/os",
    ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
    source = "pex_cfg"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        cflags=bld.env.CFLAGS_FOXBMS,
        target=f"{op}{source}",
        idx=1,
    )

    includes = [
        ".",
        "../spi",
        "../../application/config",
        "../../main/include",
    ]
    source = "spi_cfg"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        cflags=bld.env.CFLAGS_FOXBMS,
        target=f"{op}{source}",
        idx=1,
    )

    src_map = {"ltc": "adi", "maxim": "mxm"}
    man = src_map.get(
        bld.env.FOXBMS_BMS_SLAVE_AFE_MANUFACTURER,
        bld.env.FOXBMS_BMS_SLAVE_AFE_MANUFACTURER,
    )

    source = f"spi_cfg_{man}"
    bld.objects(
        source=f"{source}.c",
        includes=["."],
        cflags=bld.env.CFLAGS_FOXBMS,
        target=f"{op}{source}",
        idx=1,
    )

    source = "spi_cfg_generic"
    bld.objects(
        source=f"{source}.c",
        includes=["."],
        cflags=bld.env.CFLAGS_FOXBMS,
        target=f"{op}{source}",
        idx=1,
    )

    includes = [
        ".",
        "../sps",
        "../mcu",
        "../../application/config",
        "../../engine/config",
        "../../engine/database",
        "../../main/include",
        "../../task/os",
    ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
    source = "sps_cfg"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        cflags=bld.env.CFLAGS_FOXBMS,
        target=f"{op}{source}",
        idx=1,
    )
