#!/usr/bin/env python3
#
# Copyright (c) 2010 - 2026, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"


def build(bld):
    op = f"{bld.env.APPNAME.lower()}-object-"
    lp = f"{bld.env.APPNAME.lower()}-"

    bld.recurse(["cbs"])

    includes = [
        ".",
        "cbs",
        "../../application/config",
        "../../driver/config",
        "../../driver/mcu",
        "../../driver/io",
        "../../driver/pex",
        "../../driver/rtc",
        "../../engine/config",
        "../../engine/database",
        "../../engine/diag",
        "../../main/include",
        "../../task/config",
        "../../task/ftask",
        "../../task/os",
    ] + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
    source = "can"
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        cflags=bld.env.CFLAGS_FOXBMS,
        target=f"{op}{source}",
    )

    use = [
        f"{op}can",
        f"{op}can_helper",
        f"{op}can_config_rx",
        f"{op}can_config_tx_cyclic",
        f"{op}can_cbs_rx_f_bms-state-request",
        f"{op}can_cbs_rx_f_debug",
        f"{op}can_cbs_tx_f_crash-dump",
        f"{op}can_cbs_tx_f_debug-build-configuration",
        f"{op}can_cbs_tx_f_debug-identify-hardware",
        f"{op}can_cbs_tx_f_debug-response",
        f"{op}can_cbs_tx_f_debug-unsupported-multiplexer-values",
        f"{op}can_cbs_tx_f_fatal-error",
        f"{op}can_cbs_tx_f_bms-state-details",
        f"{op}can_cbs_tx_f_bms-state",
        f"{op}can_cbs_tx_f_cell-temperatures",
        f"{op}can_cbs_tx_f_cell-voltages",
        f"{op}can_cbs_tx_f_pack-limits",
        f"{op}can_cbs_tx_f_pack-minimum-maximum-values",
        f"{op}can_cbs_tx_f_pack-state-estimation",
        f"{op}can_cbs_tx_f_pack-values-p0",
        f"{op}can_cbs_tx_f_pack-values-p1",
        f"{op}can_cbs_tx_f_string-minimum-maximum-values",
        f"{op}can_cbs_tx_f_string-state-estimation",
        f"{op}can_cbs_tx_f_string-state",
        f"{op}can_cbs_tx_f_string-values-p0",
        f"{op}can_cbs_tx_f_string-values-p1",
        f"{op}can_cbs_tx_f_sys-state",
    ]

    if bld.is_imd_bender_iso165c():
        use.extend(
            [
                f"{op}can_cbs_rx_imd_bender-iso165c-info",
                f"{op}can_cbs_rx_imd_bender-iso165c-response",
                f"{op}can_cbs_tx_imd_bender-iso165c-request",
            ]
        )

    if bld.is_aerosol_sensor_honeywell_bas6c_x00():
        use.append(f"{op}can_cbs_rx_as_honeywell-bas6c-x00")

    if bld.is_current_sensor_isabellenhuette_ivt_s():
        use.append(f"{op}can_cbs_rx_cs_isabellenhuette-ivt-s")
    elif bld.is_current_sensor_lem_cab500():
        use.append(f"{op}can_cbs_rx_cs_lem-cab500")

    if bld.is_bms_slave_debug_can():
        use.extend(
            [
                f"{op}can_cbs_rx_afe_cell-temperatures",
                f"{op}can_cbs_rx_afe_cell-voltages",
            ]
        )
    bld(
        features="c cstlib",
        use=use,
        target=f"{lp}can",
    )
