#!/usr/bin/env python3
#
# Copyright (c) 2010 - 2026, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"

import bms_config_generate
import bms_config_validate
from waflib.Build import BuildContext


def build(bld: BuildContext) -> None:
    if bld.variant in ("app_ti_arm_cgt", "app_spa_ti_arm_cgt"):
        bms_config_node = bld.srcnode.find_node(bld.env.BMS_CONFIG)
        system = bms_config_validate.validate_bms_configuration(bld, bms_config_node)
        bms_config_generate.set_env_variables(bld, system)

        contents = [
            "aerosol_sensor",
            "algorithm",
            "balancing_strategy",
            "current_sensor",
            "imd_sensor",
            "redundant_v_t_measurement",
            "debug",
            "rtos",
            "bms_slave",
            "mcu",
        ]
        for content in contents:
            bld(
                features="foxbms_config",
                bms_config_node=bms_config_node,
                system=system,
                content=content,
                target=content,
            )

        bld(
            use=contents,
            export_includes=[bld.bldnode],
            target="foxbms_config",
        )
        foxbms_config_rtos = bld.bldnode.find_or_declare("foxbms_config_rtos.h")
        foxbms_config_debug = bld.bldnode.find_or_declare("foxbms_config_debug.h")
        bld.env.append_unique(
            "CFLAGS_HAL",
            [
                f"--preinclude={foxbms_config_rtos.abspath()}",
                f"--preinclude={foxbms_config_debug.abspath()}",
            ],
        )
        bld.env.append_unique(
            "CFLAGS_OS",
            [
                f"--preinclude={foxbms_config_rtos.abspath()}",
                f"--preinclude={foxbms_config_debug.abspath()}",
            ],
        )

        bld.recurse(["app", "os", "portable"])

    if bld.variant in (
        "bootloader_ti_arm_cgt",
        "bootloader_unit_test_ti_arm_cgt",
        "bootloader_spa_ti_arm_cgt",
    ):
        bld.recurse(["bootloader", "portable"])
