#!/usr/bin/env python3
#
# Copyright (c) 2010 - 2026, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"


from waflib.Build import BuildContext


def build(bld: BuildContext) -> None:
    bld.recurse("api")

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/driver/afe/debug/can/debug_can.c"),
            bld.path.find_node("test_debug_can.c"),
        ],
        target="test-app-debug_can",
        includes=[
            bld.srcnode.find_node("src/app/driver/afe/api"),
            bld.srcnode.find_node("src/app/driver/afe/debug/can"),
            bld.srcnode.find_node("src/app/driver/can"),
            bld.srcnode.find_node("src/app/driver/can/cbs"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/rtc"),
            bld.srcnode.find_node("src/app/engine/config"),
            bld.srcnode.find_node("src/app/engine/database"),
            bld.srcnode.find_node("src/app/task/config"),
            bld.srcnode.find_node("src/app/task/ftask"),
        ],
        mocks=[
            bld.srcnode.find_node("src/app/driver/can/cbs/can_helper.h"),
            bld.srcnode.find_node("src/app/engine/database/database.h"),
            bld.srcnode.find_node("src/app/engine/config/database_cfg.h"),
            bld.srcnode.find_node("src/app/task/ftask/ftask.h"),
            bld.srcnode.find_node("src/app/task/os/os.h"),
        ],
        defines=[
            "TEST_BS_NR_OF_STRINGS=2u",
            "TEST_BS_NR_OF_MODULES_PER_STRING=4u",
            "FOXBMS_AFE_DRIVER_DEBUG_CAN=1u",
        ],
    )
