#!/usr/bin/env python3
#
# Copyright (c) 2010 - 2026, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"


from waflib.Build import BuildContext
from waflib.Utils import is_win32

# cspell:ignore stdtypes SSWF pinmux


def build(bld: BuildContext) -> None:
    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/main/fassert.c"),
            bld.path.find_node("test_fassert.c"),
        ],
        target="test-app-fassert",
    )
    if is_win32:
        bld(
            features="c cprogram test",
            source=[
                bld.srcnode.find_node("src/app/main/fstartup.c"),
                bld.path.find_node("test_fstartup.c"),
            ],
            target="test-app-fstartup",
            includes=[
                bld.srcnode.find_node("tests/unit/app/main/helper"),
                bld.root.find_node(
                    "C:/ti/Hercules/HALCoGen/v04.07.01/drivers/TMS570LC4357ZWT/SYSTEM570v000"
                ),
            ],
            mocks=[
                bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_sys_common.h"),
                bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_hal_stdtypes.h"),
                bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_system.h"),
                bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_sys_vim.h"),
                bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_sys_core.h"),
                bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_reg_esm.h"),
                bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_esm.h"),
                bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_sys_mpu.h"),
                bld.bldnode.find_or_declare(
                    f"{bld.env.HAL_DIR[0]}/HL_errata_SSWF021_45.h"
                ),
            ],
            defines=[
                "__REG_ESM_H__",
            ],
            cflags=[
                "-include",
                "HL_hal_stdtypes.h",
                "-include",
                "HL_sys_common.h",
                "-include",
                "m_esm.h",
            ],
        )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/main/main.c"),
            bld.path.find_node("test_main_ethernet_uart.c"),
        ],
        target="test-app-main_ethernet_uart",
        includes=[
            bld.srcnode.find_node("src/app/application/ethernet"),
            bld.srcnode.find_node("src/app/driver/adc"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/dma"),
            bld.srcnode.find_node("src/app/driver/foxmath"),
            bld.srcnode.find_node("src/app/driver/i2c"),
            bld.srcnode.find_node("src/app/driver/io"),
            bld.srcnode.find_node("src/app/driver/led"),
            bld.srcnode.find_node("src/app/driver/pwm"),
            bld.srcnode.find_node("src/app/driver/spi"),
            bld.srcnode.find_node("src/app/driver/uart"),
            bld.srcnode.find_node("src/app/engine/diag"),
            bld.srcnode.find_node("src/app/engine/hw_info"),
            bld.srcnode.find_node(
                "src/os/freertos/freertos-plus/freertos-plus-tcp/source/include"
            ),
            bld.srcnode.find_node(
                "src/os/freertos/freertos-plus/freertos-plus-tcp/source/portable/Compiler/CCS"
            ),
        ],
        mocks=[
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_adc.h"),
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_crc.h"),
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_etpwm.h"),
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_gio.h"),
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_het.h"),
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_pinmux.h"),
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_sys_core.h"),
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_system.h"),
            bld.srcnode.find_node("src/app/driver/adc/adc.h"),
            bld.srcnode.find_node("src/app/engine/diag/diag.h"),
            bld.srcnode.find_node("src/app/engine/config/diag_cfg.h"),
            bld.srcnode.find_node("src/app/driver/dma/dma.h"),
            bld.srcnode.find_node("src/app/application/ethernet/ethernet.h"),
            bld.srcnode.find_node("src/app/driver/foxmath/foxmath.h"),
            bld.srcnode.find_node("src/app/driver/i2c/i2c.h"),
            bld.srcnode.find_node("src/app/driver/led/led.h"),
            bld.srcnode.find_node("src/app/engine/hw_info/master_info.h"),
            bld.srcnode.find_node("src/app/task/os/os.h"),
            bld.srcnode.find_node("src/app/driver/pwm/pwm.h"),
            bld.srcnode.find_node("src/app/driver/spi/spi.h"),
            bld.srcnode.find_node("src/app/driver/uart/uart.h"),
        ],
        defines=[
            "FOXBMS_TCP_SUPPORT=1",
            "FOXBMS_UART_SUPPORT=1",
        ],
        cflags=[
            "-I",
            "../../src/os/freertos/freertos/include",
            "-include",
            "FreeRTOSConfig.h",
        ],
    )

    bld(
        features="c cprogram test",
        source=[
            bld.srcnode.find_node("src/app/main/main.c"),
            bld.path.find_node("test_main.c"),
        ],
        target="test-app-main",
        includes=[
            bld.srcnode.find_node("src/app/driver/adc"),
            bld.srcnode.find_node("src/app/driver/config"),
            bld.srcnode.find_node("src/app/driver/dma"),
            bld.srcnode.find_node("src/app/driver/foxmath"),
            bld.srcnode.find_node("src/app/driver/i2c"),
            bld.srcnode.find_node("src/app/driver/io"),
            bld.srcnode.find_node("src/app/driver/led"),
            bld.srcnode.find_node("src/app/driver/pwm"),
            bld.srcnode.find_node("src/app/driver/spi"),
            bld.srcnode.find_node("src/app/engine/diag"),
            bld.srcnode.find_node("src/app/engine/hw_info"),
        ],
        mocks=[
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_adc.h"),
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_crc.h"),
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_etpwm.h"),
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_gio.h"),
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_het.h"),
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_pinmux.h"),
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_sys_core.h"),
            bld.bldnode.find_or_declare(f"{bld.env.HAL_DIR[0]}/HL_system.h"),
            bld.srcnode.find_node("src/app/driver/adc/adc.h"),
            bld.srcnode.find_node("src/app/engine/diag/diag.h"),
            bld.srcnode.find_node("src/app/engine/config/diag_cfg.h"),
            bld.srcnode.find_node("src/app/driver/dma/dma.h"),
            bld.srcnode.find_node("src/app/driver/foxmath/foxmath.h"),
            bld.srcnode.find_node("src/app/driver/i2c/i2c.h"),
            bld.srcnode.find_node("src/app/driver/led/led.h"),
            bld.srcnode.find_node("src/app/engine/hw_info/master_info.h"),
            bld.srcnode.find_node("src/app/task/os/os.h"),
            bld.srcnode.find_node("src/app/driver/pwm/pwm.h"),
            bld.srcnode.find_node("src/app/driver/spi/spi.h"),
        ],
    )
