#!/usr/bin/env python3
#
# Copyright (c) 2010 - 2026, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"


from waflib import Utils
from waflib.Build import BuildContext
from waflib.Tools import waf_unit_test


def build(bld: BuildContext) -> None:
    bld.recurse(["driver", "engine", "hal", "main"])

    bld.cmock_cfg = bld.srcnode.find_resource("conf/unit/bootloader_cmock.yml")
    bld.unity_cfg = bld.srcnode.find_resource("conf/unit/unity.yml")
    bld.gcovr_cfg = bld.srcnode.find_resource("conf/unit/bootloader_gcovr.cfg")

    bld.objects(
        features="c",
        target="bootloader-c-test-constants",
        export_includes=[
            bld.srcnode.find_node("src/bootloader/main/include"),
            bld.srcnode.find_node("src/os/freertos/freertos/include"),
            bld.srcnode.find_node(
                "src/os/freertos/freertos/portable/ccs/arm_cortex-r5"
            ),
            bld.srcnode.find_node("tests/unit/support"),
        ],
        export_defines=[
            "UNITY_UNIT_TEST",
            "FAS_ASSERT_LEVEL=2",
            "UNITY_INCLUDE_EXEC_TIME",
        ],
        use=["foxbms-bootloader-hal"],
    )
    if not Utils.is_win32:
        t = bld.get_tgen_by_name("bootloader-c-test-constants")  # cspell:ignore tgen
        t.export_defines.append("_POSIX_C_SOURCE=200809L")
    bld.add_post_fun(waf_unit_test.summary)
    bld.add_post_fun(waf_unit_test.set_exit_code)
