#!/usr/bin/env python3
#
# Copyright (c) 2010 - 2026, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"


from waflib import Logs, Utils


def build(bld):
    op = f"{bld.env.APPNAME.lower()}-object-"
    lp = f"{bld.env.APPNAME.lower()}-"

    includes = [
        "../driver/config",
        "../driver/emac",
        "../main/include",
    ]
    source = "app-hl_notification"
    bld.objects(
        source=f"{source}.c",
        target=f"{op}{source}",
        includes=includes,
        idx=1,
    )

    cflags = bld.env.CFLAGS_HAL
    bld.env.append_unique("HCG_GEN_HAL_INC_PATHS", [bld.path.get_bld().relpath()])
    source = None
    remove = None
    startup_hash = None
    if Utils.is_win32 or bld.env.HALCOGEN:
        startup_hash = bld.path.find_node("app-startup.hash")
        remove = bld.path.find_node("../../../conf/hcg/app-remove.yml")
        source = ["../../../conf/hcg/app.hcg"]
    else:
        hal_src_dir = bld.path.get_bld().find_dir("source")
        hal_inc_dir = bld.path.get_bld().find_dir("include")
        Logs.warn(
            "HALCogen is not available and therefore the code generator can not run.\n"
            f"Assuming HAL sources are available at {hal_src_dir} and {hal_inc_dir}."
        )
        if hal_src_dir:
            source = hal_src_dir.ant_glob("*.c") + hal_src_dir.ant_glob("*.asm")
    if source:
        if bld.env.FOXBMS_TCP_SUPPORT:
            includes.extend(
                bld.env.FOXBMS_INCLUDES_RTOS_KERNEL
                + bld.env.FOXBMS_INCLUDES_RTOS_KERNEL_ADDONS
            )

        bld(
            features="c cstlib",
            source=source,
            cflags=cflags,
            use=f"{op}app-hl_notification",
            target=f"{lp}hal",
            startup_hash=startup_hash,
            remove=remove,
            idx=1,
        )
