#!/usr/bin/env python3
#
# Copyright (c) 2010 - 2026, Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# We kindly request you to use one or more of the following phrases to refer to
# foxBMS in your hardware, software, documentation or advertising materials:
#
# - "This product uses parts of foxBMS®"
# - "This product includes parts of foxBMS®"
# - "This product is derived from foxBMS®"


from waflib import Logs, Utils
from waflib.Build import BuildContext


def build(bld: BuildContext) -> None:
    op = f"{bld.env.APPNAME.lower()}-object-"
    lp = f"{bld.env.APPNAME.lower()}-"
    ip = f"{bld.env.APPNAME.lower()}-incpath-"

    includes = [
        bld.srcnode.find_node("src/app/driver/config"),
        bld.srcnode.find_node("src/app/driver/emac"),
        bld.srcnode.find_node("src/app/main/include"),
    ]
    source = "app-hl_notification"
    use = [
        f"{ip}hal",
        "foxbms_config",
    ]
    bld.objects(
        source=f"{source}.c",
        includes=includes,
        preinclude_deps=[
            bld.bldnode.find_or_declare("foxbms_config_rtos.h"),
            bld.bldnode.find_or_declare("foxbms_config_debug.h"),
        ],
        use=use,
        target=f"{op}{source}",
    )

    bld(
        export_includes=[bld.path.get_bld().find_or_declare("include")],
        target=f"{ip}hal",
    )

    source = None
    remove = None
    startup_hash = None
    if Utils.is_win32 or bld.env.HALCOGEN:
        startup_hash = bld.path.find_node("app-startup.hash")
        remove = bld.srcnode.find_node("conf/hcg/app-remove.yml")
        source = [bld.srcnode.find_node("conf/hcg/app.hcg")]
    else:
        hal_src_dir = bld.path.get_bld().find_dir("source")
        hal_inc_dir = bld.path.get_bld().find_dir("include")
        Logs.warn(
            "HALCogen is not available and therefore the code generator can not run.\n"
            f"Assuming HAL sources are available at {hal_src_dir} and {hal_inc_dir}."
        )
        if hal_src_dir:
            c_sources = list(hal_src_dir.ant_glob("*.c"))
            asm_sources = list(hal_src_dir.ant_glob("*.asm"))
            source = c_sources + asm_sources
    if source:
        use = [
            f"{op}app-hl_notification",
            "foxbms_config",
        ]
        if bld.env.FOXBMS_TCP_SUPPORT:
            use.append(f"{ip}rtos-kernel")
            use.append(f"{ip}rtos-tcp")
        bld(
            features="asm c cstlib",
            source=source,
            preinclude_deps=[
                bld.bldnode.find_or_declare("foxbms_config_rtos.h"),
                bld.bldnode.find_or_declare("foxbms_config_debug.h"),
            ],
            use=use,
            uselib="HAL",
            startup_hash=startup_hash,
            remove=remove,
            target=f"{lp}hal",
        )
